; -----------------------------------------------
; Komunikacny uzol medzi E200(0) a LETVIS
; ACC Bratislava
;
; -----------------------------------------------


;---------------
; ADRESY                            ; IMPLICITNE
;תתתתתתתתתתתתתתת

  FIR           = LZIB
  THIS NODE     = MI
  REMOTE NODE   = BR

  THIS X25      = 158 20 44 02      ; LETVIS2
  REMOTE X25    = 158 20 20 03      ; ASTA1
; REMOTE X25    = 158 20 20 04      ; ASTA2
; REMOTE X25    = 158 20 44 01      ; E2000
; REMOTE X25    = 158 10 20 04      ; BULL
; REMOTE X25    = 158 10 20 51      ; PC
; REMOTE X25    = 158 20 20 03      ; VYVOJ

; THIS NSAP     = 73 51 00          ; povodne pridelene NSAP,
  THIS NSAP     = 73 38 01          ; novo pridelene NSAP,
  REMOTE NSAP   = 73 38 00          ; malo by platit v realnej prevadzke


;---------------
; OLDI
;תתתתתתתתתתתתתתת

;  rec_buf_size = 15;               ; velkost prijimacieho buffera (az neskor a automaticky pri zmene)
;  pkt_size     = 4124              ; nastavit zatial manualne do X25.camus.cfg

  Ts_TimeOut   = 40
  Tr_TimeOut   = 80

  send_StartUp = yes               ; povolenie vysielania StartUp


;---------------
; EXT
;תתתתתתתתתתתתתתת

  process-all  = no                ; imlicitne
  HeartBeat    = (CH)Ù


;---------------
; CAMUS/ASTA
;תתתתתתתתתתתתתתת

  LAM_TimeOut       = 40

  asta-interface    = yes          ; pripojeno na ASTA nie na THOMSON
  debug_ACT         = no           ; povolenie odosielania cvicnych sprav ACT


;---------------
; FDP
;תתתתתתתתתתתתתתת

  point distance    = 5000         ; maximalny pripustny rozdiel medzi bodmi OPL a CAMUS
  FL from altitude  = FL60         ; od uvedenej vysky sa letove hladiny pre CAMUS uvadzaju vo feetoch

  send VFR FPL      = no           ;
  send ERROR to FDO = yes          ; imlicitne zapnute
  send NOLAM to FDO = yes          ; imlicitne potlacene

  15a               = true         ; povodne nastavenie pre nehlasenu zmenu protokolu - ci je pole 15a uvedene v sprave, teraz sa testuje automaticky


  exclude-points    = XZ           ; vstupne body do sektorov pre trate LPS zacinajuce na tuto kombinaciu su ignorovane
  exclude-points    = XX           ; maximalne dalsich 19 vynimiek
; exclude-points    =
; exclude-points    =
; exclude-points    =
; exclude-points    =
; exclude-points    =
; exclude-points    =


;---------------
; Xת25
;תתתתתתתתתתתתתתת

  exception_call_desc = no;

