; -------------------------------------------------
; MACC Praha
; Komunikacny uzol medzi LETVIS FDP/S a OPL 
; -------------------------------------------------


;---------------
; ADRESY
;תתתתתתתתתתתתתתת

  FIR         = LK
  THIS NODE   = MI
  REMOTE NODE = PL


;---------------
; UDP PORT
;תתתתתתתתתתתתתתת

  UDP-PORT    = $400
  IP-ADR      = 10.192.48.60


;---------------
; COM PORT
;תתתתתתתתתתתתתתת

  COM         = 2
  MODE        = 9600
  BITS        = 7
  STOP_BITS   = 1
  PARITY      = EVEN



;---------------
; Komunikacia
;תתתתתתתתתתתתתתת

  Tr_TimeOut  = 40
  Ts_TimeOut  = 40


;---------------
; Spracovanie
;תתתתתתתתתתתתתתת

  stream            = yes    ;
  send VFR FPL      = yes
  send error to FDO = yes    ; imlicitne
  FL from altitude  = no

  FUA time limits   = no     ; imlicitne povolene, ale od OPL prichdzaju spravy od 00.00 do 23.59, co blokuje dalsie spracovanie


  FL5-MIN = 110
  FL5-MAX = 160