;-----------------------
; FIR DESCRIBTION
;תתתתתתתתתתתתתתתתתתתתתתת

  AIRBASE = LKPR
; SECTORS = 


;-----------------------
; SSR MANAGEMENT
;תתתתתתתתתתתתתתתתתתתתתתת

; SSR = 6116-6130


;-----------------------
; SYSTEM
;תתתתתתתתתתתתתתתתתתתתתתת

  win.tmp = D:\


;-----------------------
; FDP OPTIONS
;תתתתתתתתתתתתתתתתתתתתתתת

  edit FPLM            = yes ; povolenie editacie vojenskeho a ineho stripu
  edit FPLC            = yes ; povolenie editacie civilneho stripu

  estimate ARR         = yes ; prepocet casu pristatia prijateho civilneho stripu,
                             ; ak to je vo FIR;
                             ; plati pre server pri prijme od externej linky
                             ; a pracovne stanice pri podani stripu


; NET ACK ALL          = no  ; implictne


 FL VFR = 300