; -------------------------------------------------
; MACC Praha
; Komunikacny uzol medzi LETVIS FDP/S a VERA
; -------------------------------------------------


;---------------
; ADRESY
;תתתתתתתתתתתתתתת

  FIR         = LK
  THIS NODE   = MI
  REMOTE NODE = VR


;---------------
; UDP PORT
;תתתתתתתתתתתתתתת

  UDP-PORT    = $5110
  IP-ADR      = 10.192.48.45


;---------------
; Komunikacia
;תתתתתתתתתתתתתתת

; Tr_TimeOut  = 40
; Ts_TimeOut  = 40

