; -------------------------------------------------------
; nazov    ; uzol   , adresa ; protokol, doplnkove udaje
; -------------------------------------------------------

; nodes address

; Blava    ; SRLP   , #158204499  ; @THIS

; adapter settings

