; ---------------------------------------------
; symbols maps to update
; תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת

  SYMBOL FILE = NDB
  SYMBOL FILE = AIP-C
  SYMBOL FILE = AIP-M
  SYMBOL FILE = AIP-A
  SYMBOL FILE = TP


; ---------------------------------------------
; symbols to edit
; תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת

  SYMBOL MENU = NDB
  SYMBOL MENU =         ; empty menu line
  SYMBOL MENU = AIP-C
; SYMBOL MENU = AIP-M
; SYMBOL MENU = AIP-A
  SYMBOL MENU = TP


; --------------------------------
; symbol colors (gray palette)
; תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת

  AIP C     = 25
  AIP V     = 25
  AIP O     = 24

  SP        = 23
  REP1      = 23
  REP2      = 23
  NDB1      = 23
  NDB2      = 23
  VOR       = 23
  VOR/DME1  = 23
  VOR/DME2  = 23

  TP        = 23


; --------------------------------
; map colors
; תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת

  FIR F     = 33
  FIR       = 21

  ACC F     = 34
  ACC       = 22
  ACC SEC F = 35
  ACC SEC   = 22

  APP F     = 34
  APP       = 22
  APP SEC F = 35
  APP SEC   = 22

  AWY F     = 35
  AWY       = 37
  AWY_      = 22
  ILS_      = 21

  TMA F     = 36
  TMA       = 38
  CTR F     = 37
  CTR       = 38

  ACT P     = 41
  ACT A     = 40
  TSA P     = 49
  TSA A     = 48
  PRS P     = 49
  PRS A     = 48

  R F       = 45
  R         = 46
  P F       = 4
  P         = 4

  PAV0      = 19
  PAV1      = 20

  LDM0      = 19
  LDM1      = 19
  LDM2      = 19

  MARK      = 22

  DESC      = 14


;  GRP_ACT_  = 0   ;    { potlacenie olemovanie aktivovanych priestorov }