 {$IFDEF SLOVAK}

   const mnu_STRIP  = '~S~TRIP';
         tit_STRIP  = 'FORMT STRIPU';

         MINI       = ' ~M~INI STRIPY     (Shift+F2) ';
         SHORT      = ' ~K~RTKE STRIPY    (Ctrl+F2) ';
         LARGE      = ' ~—~PLN STRIPY      (Alt+F2) ';

         LINE       = ' —~Z~KE STRIPY ';


   const mnu_BOARD  = 'TA~B~LET';
         tit_BOARD  = 'NASTAVENIE TABLETU';

         PROPOSED   = ' ~D~ORU€EN STRIPY... ';
         PROPOSED_  = ' DORU€EN STRIPY ';
          _ACC_FPLC = 'PREVZATIE ~C~IVILNCH STRIPOV';
          _ACC_FPLM = '  -//-    ~V~OJENSKCH STRIPOV';
          _ACC_FPLO = '  -//-    STRIPOV ~I~NCH LETOV';
          _PRN_REC  = '~T~LA€ DORU€ENCH STRIPOV';
          _PRN_PA   = 'AKO N~A~RHOVANCH/PREVZATCH';
          _PRN_FPLC = 'TLA€ CIVI~L~NCH STRIPOV';
          _PRN_FPLM = '-//- ~V~OJE~N~SKCH STRIPOV';
          _PRN_FPLO = '-//- STRIPOV IN~~CH LETOV';

         ARRANGE    = ' ~U~SPORIADANIE NA TABLETE... ';
         ARRANGE_   = ' USPORIADANIE NA TABLETE ';
          _IN_HD    = 'PODœA VSTUPNCH/TRA†OVCH BODOV';
          _OTHERS   = 'NEZARADEN DO OSTATNCH ("OTHERS")';
          _NDB_XY   = 'RADENIE PODœA S—RADN‹C BODOV';
          _EMPTY    = 'ZOBRAZENIE PRZDNYCH SKUP‹N';
          _D_SEC_FIR= 'DISPLAY IN SECTOR/FIR';
          _IN_TH    = 'IN/THROUGH SECTOR';
          _I_SEC_FIR= 'INPUT ON SECTOR/FIR';
          _RTE_SEC  = 'ROUTE IN SECTOR';
          _EQ_NDB   = '~Z~TOTO’NENIE BODOV';

         DIFFER     = ' R~O~ZL‹›ENIE STRIPOV... ';
         DIFFER_    = ' PODLO’KY POD STRIPY ';
          _SMER     = 'R~O~ZL‹›ENIE ~S~MERU LETU';
          _D1       = '~1~. VCHOD-ZPAD';
          _D2       = '~2~. ZPAD-VCHOD';
          _D3       = '~3~. VN—TRO›TTNE';
          _D4       = '~4~. VSTUPUJ—CE';
          _D5       = '~5~. ODLIETAJ—CE';
          _D6       = '~6~. VOJESNK';
          _D7       = '~7~. IN';

         PRESENT    = ' ~Z~OBRAZENIE STRIPU... ';
         PRESENT_   = ' ~Z~OBRAZENIE POL‹ STRIPOV ';
          _IN_FL    = 'PREPO€ET V›KY S->FL';
          _IN_KM    = 'PREPO€ET RCHLOSTI N->K';
          _COR      = 'INDIKCIA OPRAVY';
          _LAM      = 'INDIKCIA POTVRDENIA';
          _MSTRIP   = 'DEK•DOVAN TRA† VOJENSKHO/INHO STRIPU';
 {$ENDIF}


 {$IFDEF CZECH}

   const mnu_STRIP  = '~S~TRIP';
         tit_STRIP  = 'FORMT STRIPU';

         MINI       = ' ~M~INI STRIPY     (Shift+F2) ';
         SHORT      = ' ~K~RTKE STRIPY    (Ctrl+F2) ';
         LARGE      = ' ~—~PLN STRIPY      (Alt+F2) ';

         LINE       = ' —~Z~KE STRIPY ';


   const mnu_BOARD  = 'TA~B~LET';
         tit_BOARD  = 'NASTAVEN‹ TABLETU';

         PROPOSED   = ' ~D~ORU€EN STRIPY... ';
         PROPOSED_  = ' DORU€EN STRIPY ';
          _ACC_FPLC = 'PžEVZET‹ ~C~IVILN‹CH STRIP¦';
          _ACC_FPLM = '  -//-   ~V~OJENSKCH STRIP¦';
          _ACC_FPLO = '  -//-   STRIP¦ J~I~NCH LET¦';
          _PRN_REC  = '~T~ISK DORU€ENCH STRIP¦';
          _PRN_PA   = 'JAKO N~A~RHOVANCH/PžEVZETCH';
          _PRN_FPLC = 'TISK CIVI~L~N‹CH STRIP¦';
          _PRN_FPLM = '-//- ~V~OJE~N~SKCH STRIP¦';
          _PRN_FPLO = '-//- STRIP¦ JIN~~CH LET¦';

         ARRANGE    = ' ~U~SPOžDN‹ NA TABLETU... ';
         ARRANGE_   = ' USPOžDN‹ NA TABLETU ';
          _IN_HD    = 'PODLE VSTUPN‹CH/TRA†OVCH BOD¦';
          _OTHERS   = 'NEZAžAZEN K OSTATN‹M ("OTHERS")';
          _NDB_XY   = 'žAZEN‹ PODLE SOUžADNIC BOD¦';
          _EMPTY    = 'ZOBRAZEN‹ PRZDNCH SKUPIN';
          _D_SEC_FIR= 'DISPLAY IN SECTOR/FIR';
          _IN_TH    = 'IN/THROUGH SECTOR';
          _I_SEC_FIR= 'INPUT ON SECTOR/FIR';
          _RTE_SEC  = 'ROUTE IN SECTOR';
          _EQ_NDB   = '~Z~TOTO’NEN‹ BOD¦';

         DIFFER     = ' R~O~ZLI›EN‹ STRIP¦... ';
         DIFFER_    = ' PODLO’KY POD STRIPY ';
          _SMER     = 'R~O~ZLI›EN‹ ~S~M‰RU LETU';
          _D1       = '~1~. VCHOD-ZPAD';
          _D2       = '~2~. ZPAD-VCHOD';
          _D3       = '~3~. VNITROSTTN‹';
          _D4       = '~4~. VSTUPUJ‹CI';
          _D5       = '~5~. ODLETJ‹CI';
          _D6       = '~6~. VOJESNK';
          _D7       = '~7~. JIN';

         PRESENT    = ' ~Z~OBRAZEN‹ STRIP¦... ';
         PRESENT_   = ' ~Z~OBRAZEN‹ POL‹ STRIP¦ ';
          _IN_FL    = 'PžEPO€ET V›KY S->FL';
          _IN_KM    = 'PžEPO€ET RYCHLOSTI N->K';
          _COR      = 'INDIKACE OPRAVY';
          _LAM      = 'INDIKACE POTVRZEN‹';
          _MSTRIP   = 'DEK•DOVAN TRA† VOJENSKHO/JINHO STRIPU';
 {$ENDIF}


 {$IFDEF ENGLISH}

   const mnu_STRIP  = '~S~TRIP';
         tit_STRIP  = 'STRIP''s FORMAT';

         MINI       = ' ~M~INI  STRIPs  (Shift+F2) ';
         SHORT      = ' ~S~HORT STRIPs   (Ctrl+F2) ';
         LARGE      = ' ~L~ARGE STRIPs    (Alt+F2) ';
         LINE       = ' L~I~NE STRIPs ';


   const mnu_BOARD  = '~B~OARD';
         tit_BOARD  = ' BOARD OPTIONs ';

         PROPOSED   = ' ~R~ECEIVED STRIPs... ';
         PROPOSED_  = ' RECEIVED STRIPs ';
          _ACC_FPLC = 'CONFIRM ~E~N-ROUTE';
          _ACC_FPLM = ' -//-   ~M~ILITARY';
          _ACC_FPLO = ' -//-   ~O~THER FPL';


         ARRANGE    = ' BOARD ~A~RRANGEMET... ';
         ARRANGE_   = ' ARRANGE BOARD ';
          _IN_HD    = 'BY INPUT/HEADING POINTS ';
          _OTHERS   = 'ORDERING TO OTHERS';
          _NDB_XY   = 'ORDERING BY COORDINATES';
          _EMPTY    = 'DISPLAY EMPTY GROUPS ';

          _D_SEC_FIR   = 'DISPLAY IN SECTOR/FIR';
          _IN_TH       = 'DISPLAY IN/THROUGH SECTOR';
          _I_SEC_FIR   = 'INPUT ON SECTOR/FIR';
          _RTE_SEC     = 'ROUTE IN SECTOR';
          _S_IN_KM     = 'INPUT POINT DISTANCE TO SECTOR';
          _S_EST_LIMIT = 'ACTIVATE STRIP ON SECTOR';
          _S_DEL_LIMIT = 'RELEASE STRIP FROM SECTOR';

          _EQ_NDB   = 'EQUALIZE NDB ';


         DIFFER     = ' STRIPs DI~F~FERENTIATE... ';
         DIFFER_    = ' STRIP''s PADs ';
          _SMER     = 'DIFFERENTIATE ~F~LIGHT COURSE';
          _D1       = '~1~. WEST->EAST ';
          _D2       = '~2~. EAST->WEST ';
          _D3       = '~3~. INTERNAL ';
          _D4       = '~4~. INBOUND  ';
          _D5       = '~5~. OUTBOND  ';
          _D6       = '~6~. MILITARY ';
          _D7       = '~7~. OTHERS   ';

         PRESENT    = ' STRIP ~P~RESENTATION... ';
         PRESENT_   = ' STRIP ARRAYS ';
          _IN_FL    = 'S->FL ALTITUDE';
          _IN_KM    = 'N->K SPEED';
          _COR      = 'CHG INDICATION';
          _LAM      = 'LAM INDICATION';
          _MSTRIP   = 'MIL STRIP/FPL';

         PRINTED    = ' STRIP PR~I~NTING... ';
          _PRN_REC  = 'PRINT RECEIVED STRIPS';
          _PRN_CHG  = 'PRINT RECEIVED CORRECTIONS';
          _PRN_PA   = 'PRINT AS P~R~OPOSED/ACCEPTED';
          _PRN_FPLC = 'PRINT E~N~-ROUTE';
          _PRN_FPLM = '-//-  M~I~LITARY';
          _PRN_FPLO = '-//-  O~T~HER FPL';
          _PRN_S    = 'PRINT IN SECTOR/FIR';
          _PRN_IN   = '-//- IN/THROUGH SECTOR';
          _PRN_EST  = 'PRINT BEFORE SECTOR';
  {$ENDIF}
