    const

         {$IFDEF SLOVAK}

           title_ARRANGE     = 'NASTAVENIE TABLETU';

           {mnu_DEFAULT_GROUP = ' ~Z~èKLADNê SKUPINY';
           mnu_DEFINED_GROUP = ' ~D~EFINOVANê SKUPINY';}

           ACCDEFINE  = ' ~R~OZLOíENIE SKUPãN      (F3) ';
           ACCDEFAULT = ' ~D~EFINOVANê SKUPINY... ';
            ACCGREAD  = ' ~N~AÄãTANIE SKUPãN... ';
            ACCGREAD_ = 'NAÄãTANIE SKUPãN STRIPOV';


           SORTING    = ' ~T~RIEDENIE V SKUPINèCH... ';
           SORTING_   = ' TRIEDENIE STRIPOV PODúA ';
            _GLOB     = '~S~POLOÄNê NASTAVENIE';
            _POINT    = '~N~èZVU VZÜAíNêHO BODU';
            _INDEX    = '~I~DENTIFIKèCIE   (INDEX)';
            _ETD      = '~Ä~ASU NA BODE    (ETD/ETO)';
            _FL       = '~L~ETOVEJ HLADINY (FL)';

         {$ENDIF}


         {$IFDEF CZECH}

           title_ARRANGE     = 'NASTAVENã TABLETU';

           {mnu_DEFAULT_GROUP = ' ~Z~èKLADNã SKUPINY';
           mnu_DEFINED_GROUP = ' ~D~EFINOVANê SKUPINY';}

           ACCDEFINE  = ' ~R~OZLOíENã SKUPIN      (F3) ';
           ACCDEFAULT = ' ~D~EFINOVANê SKUPINY... ';
            ACCGREAD  = ' ~N~AÄTENã SKUPIN... ';
            ACCGREAD_ = 'NAÄTENã SKUPIN STRIP¶';


           SORTING    = ' ~T~ûãDENã VE SKUPINèCH... ';
           SORTING_   = ' TûãDENã STRIP¶ PODLE ';
            _GLOB     = '~S~POLEÄNê NASTAVENã';
            _POINT    = '~N~èZVU VZTAíNêHO BODU';
            _INDEX    = '~I~DENTIFIKACE    (INDEX)';
            _ETD      = '~Ä~ASU NA BODU    (ETD/ETO)';
            _FL       = '~L~ETOVê HLADINY  (FL)';

         {$ENDIF}


         {$IFDEF ENGLISH}

           title_ARRANGE     = 'BOARD ARRANGEMENT';

           {mnu_DEFAULT_GROUP = ' ~D~EFAULT GROUPS';
           mnu_DEFINED_GROUP = ' D~E~FINED GROUPS';}

           SORTING    = ' BOARD ~S~ORTING... ';
           SORTING_   = ' STRIPs SORT BY ';
            _GLOB     = '~C~OMMNON SETTING';
            _POINT    = '~N~AME OF POINT';
            _INDEX    = '~I~NDEX';
            _ETD      = '~E~TD/ETO';
            _FL       = '~F~LIGHT LEVEL';

           ACCDEFINE  = ' ~D~EFINE GROUPs      (F3) ';
           ACCDEFAULT = ' D~E~FAULT GROUPs ';
            ACCGREAD  = ' D~E~FINED GROUPs... ';
            ACCGREAD_ = 'DEFINED GROUPs';
         {$ENDIF}
