{$IFDEF LKPR_MACC}

  { -------------- }
  { MACC Praha     }
  { -------------- }

    {$DEFINE LK}
    {$DEFINE CZ}
    {$DEFINE PRAHA}

    {$DEFINE ENGLISH}
    {$DEFINE HELP_CZ}

    {$DEFINE RLP}
    {$DEFINE MACC}       {$DEFINE PRAHA}
    {$DEFINE MATCA}
    { DEFINE ATCA}



  { ------------------
     Funkcie
    ------------------
  }
    { DEFINE EDD_17}               { Zmensene EDD na 17 palcovy display }
    {$DEFINE FL_DIR}               { Smer letu urceny urceny letovou hladinou }
    { DEFINE LINE_STRIP}           { Strip na riadok }

    {$DEFINE TABLET_DEP_ARR}
    {$DEFINE TABLET_WEST_EAST}

    { DEFINE SECTORS}
    {$DEFINE CAS_RTR}

    {$DEFINE PRN}
    {$DEFINE IER}


    {$DEFINE L4444M}
    {$DEFINE RVSM}

    {$DEFINE FPL}
      {$DEFINE FPL4}

      {$DEFINE FPLO}
      { DEFINE FPLM_L}           { velke FPL }

      {$DEFINE FPL0}
        {$DEFINE FPLC_ION}


    {$DEFINE RDP}
    {$DEFINE RDP_ACCEPT}


  { ------------------
     NET
    ------------------
  }
    {$DEFINE DATA_BIN}

    { DEFINE IPX}
       { DEFINE RTR1}

    {$DEFINE PCTCP}
       {$DEFINE UDP}
       {$DEFINE RTR2}

 {$ENDIF}
