  {$IFDEF LKPR_FDA}

  { -------------- }
  { MACC Praha     }
  { -------------- }

    {$DEFINE CZ}         {$DEFINE ENGLISH}  {$DEFINE HELP_CZ}
    {$DEFINE MACC}       { DEFINE PRAHA}
    {$DEFINE RLP}
    { DEFINE FDA}

    { DEFINE MATCA}
    { DEFINE ATCA}


  { ------------------
     Funkcie
    ------------------
  }
    {$DEFINE EDD_17}               { Zmensene EDD na 17 palcovy display }
    {$DEFINE FL_DIR}               { Smer letu urceny urceny letovou hladinou }
    {$DEFINE LINE_STRIP}           { Strip na riadok }

    {$DEFINE TABLET_DEP_ARR}
    {$DEFINE TABLET_WEST_EAST}

    { DEFINE SECTORS}
    {$DEFINE CAS_RTR}

    {$DEFINE FPL}
      {$DEFINE FPL0}
      {$DEFINE FPL4}

    {$DEFINE RDP}
    {$DEFINE RDP_ACCEPT}

    {$DEFINE PRN}        {$DEFINE IER}


  { ------------------
     NET
    ------------------
  }
    { DEFINE IPX}
        { DEFINE RTR1}

    {$DEFINE PCTCP}
       {$DEFINE UDP}
       {$DEFINE RTR2}

  {$ENDIF}
