const  {$IFDEF SLOVAK}
        tit_PRO  = 'NAVR~H~OVANê STRIPY';
        tit_PRO_ = 'NAVRHOVANê STRIPY';
        tit_ACC  = ' ~P~REVZIAÜ ';
        tit_DEC  = ' ~Z~RUõIÜ   ';
       {$ENDIF}

       {$IFDEF CZECH}
        tit_PRO  = 'NAVR~H~OVANê STRIPY';
        tit_PRO_ = 'NAVRHOVANê STRIPY';
        tit_ACC = ' ~P~ûEVZãT ';
        tit_DEC = ' ~Z~RUõIT  ';
       {$ENDIF}

       {$IFDEF ENGLISH}
        tit_PRO  = 'P~R~OPOSED STRIPS';
        tit_PRO_ = 'PROPOSED';
        tit_ACC  = ' ~A~CCEPT  ';
        tit_DEC  = ' ~D~ECLINE ';
       {$ENDIF}

