      {$IFDEF SLOVAK}
        const  mnu_DVZ_PLAN  = ' SPRACOVANIE ~í~IADOSTã O DIVERZIU... ';

               DVZ_PLAN      = ' P~O~DANê íIADOSTI O DIVERZIU ';
               DVZ_REC       = ' PRI~J~ATê íIADOSTI O DIVERZIU ';
               DVZ_ALL       = tit_VSETKY +'íIADOSTI O DIVERZIU  Ctrl+F9';
               {DVZ_ACT       = ' SCHVèLENê A DRíANê ~D~IVERZIE  Alt+F9 ';}

               DVZ_PPL       = ' P~R~IPRAVENê íIADOSTI ';
               DVZ_ARCH      = ' ARCH~I~VOVANê íIADOSTI ';

               DVZM          = ' ~D~IVERZIE LETãSK ';

               DVZPLANREQ    = 'OKAMíITê ODOSLANIE PLèNU AKO íIADOSTI ';
               DVZREP        = 'HLèSENIA NA DRíANê DIVERZIE ';
               DVZREPALL     = 'HLèSENIA NA VõETKY DIVERZIE ';
               DVZVAR        = 'UPOZORNENIE NA HLèSENIE O DIVERZII ';

      {$ENDIF}


      {$IFDEF CZECH}
        const  DVZM          = ' ~D~IVERZE LETIõÜ ';
               DVZREP        = 'HLèõENã O DIVERZãCH DRíENùCH LETIõTI';

      {$ENDIF}