   {$IFDEF SLOVAK}
     const
            mnu_RPL   = '~R~PL';
            tit_RPL   = 'REPETITIVE FLIGHT PLANS';

            mnu_PLN   = 'PL~N~';
            tit_PLN   = 'FLIGHT CLEARANCES';

            mnu_FPL4  = '~F~PL';
            tit_FPL4  = 'ATS-ROUTE FLIGHT PLANS';

            mnu_FPLM  = '~F~PL';
            tit_FPLM  = 'LETOVê PLèNY MIMO TRATã LPS';

            mnu_KRL   = '~K~RL';
            tit_RKL   = 'KRãDLA';

            mnu_ZAM   = '~Z~AM';
            tit_ZAM   = 'ZAMESTNANIA LETISKA';

            mnu_QGO   = '~Q~GO';
            tit_QGO   = 'SCHOPNOSÜ LETISKA';

            mnu_DVZ   = '~D~VZ';
            tit_DVZ   = 'DIVERZIE LETãSK';

            mnu_PRZ   = 'P~R~Z';
            tit_PRZ   = 'íIADOSTI O PRIDELENIE PRIESTOROV';

            mnu_PRS   = '~P~RS';
            tit_PRS   = 'VYUíITIE VZDUõNêHO PRIESTORU';

            mnu_SPR   = '~S~PR';
            tit_SPR   = 'SPRèVY/TELEGRAMY';


            mnu_MAPA  = 'MA~P~A';

            mnu_PLANZET = 'P~L~ANíET';
            tit_PLANZET = 'NASTAVENIE PLANíETU';


            mnu_NAJDI = 'Nè~J~DI';
            tit_NAJDI = 'VYHúADANIE';

            mnu_STREAM = 'V~/~V';
            tit_STREAM = 'VSTUP/VùSTUPNê DèTA';

            mnu_UDAJE  = 'D~è~TA';
            tit_UDAJE  = 'PLèNY, SPRèVY/NOTAMY';

            mnu_MMI    = 'M~M~I';
            tit_MMI    = 'VLASTNOSTI PROSTREDIA';

            mnu_OPT    = 'NASTA~V~';
            tit_OPT    = 'SPRACOVANIE óDAJOV';

            mnu_SYSTEM = 'S~Y~STêM';
            tit_SYSTEM = 'VLASTNOSTI PROGRAMU';


            mnu_OPTi       = ' NASTA~V~ENIA ';
            tit_OPTi       = 'NASTAVENIA SPRACOVANIA';

            mnu_PREHLAD     = ' PûE~H~LED... ';
            mnu_SPRACOVANIE = ' ~Z~PRACOVèNã... ';
            mnu_ZOBRAZENIE  = ' Z~O~BRAZENã... ';
            mnu_DEKODOVANIE = ' ~D~EKïDOVANã... ';
            mnu_EDITOVANIE  = ' ~P~ODènã... ';
            mnu_TLAC        = ' T~I~SK... ';

            mnuPREHLAD     = ' PRE~H~úAD ';
            mnuSPRACOVANIE = ' SPRACOVANIE ';
            mnuDEKODOVANIE = ' DEKODOVANIE ';
            mnuZOBRAZENIE  = ' ZOBRAZENIE ';
            mnuTLAC        = ' TLAÄ ';

            mnuKONFIGURACIA = ' KONFI~G~URèCIA ';
   {$ENDIF}


   {$IFDEF CZECH}
     const
            mnu_RPL   = '~R~PL';
            tit_RPL   = 'REPETITIVE FLIGHT PLANS';

            mnu_PLN   = 'PL~N~';
            tit_PLN   = 'FLIGHT CLEARANCES';

            mnu_FPL4  = '~F~PL';
            tit_FPL4  = 'ATS-ROUTE FLIGHT PLANS';

            mnu_FPLM  = '~F~PL';
            tit_FPLM  = 'LETOVê PLèNY MIMO TRATã LPS';

            mnu_KRL   = '~K~RL';
            tit_RKL   = 'KRãDLA';

            mnu_ZAM   = 'Z~A~M';
            tit_ZAM   = 'ZAMESTNANIA LETISKA';

            mnu_QGO   = '~Q~GO';
            tit_QGO   = 'SCHOPNOSÜ LETISKA';

            mnu_DVZ   = '~D~VZ';
            tit_DVZ   = 'DIVERZIE LETãSK';

            mnu_PRZ   = 'PR~Z~';
            tit_PRZ   = 'íIADOSTI O PRIDELENIE PRIESTOROV';

            mnu_PRS   = '~P~RS';
            tit_PRS   = 'VYUíITIE VZDUõNêHO PRIESTORU';

            mnu_SPR   = '~S~PR';
            tit_SPR   = 'SPRèVY/TELEGRAMY';


            mnu_MAPA  = 'MA~P~A';

            mnu_PLANZET = 'P~L~ANíET';
            tit_PLANZET = 'NASTAVENã PLANíETU';


            mnu_NAJDI  = 'NA~J~DI';
            tit_NAJDI  = 'VYHLEDèNã';

            mnu_STREAM = 'V~/~V';
            tit_STREAM = 'VSTUP/VùSTUPNã DATA';

            mnu_UDAJE  = 'D~A~TA';
            tit_UDAJE  = 'PLèNY, ZPRèVY/NOTAMY';


            mnu_MMI    = 'M~M~I';
            tit_MMI    = 'VLASTNOSTI PROSTûEDã';

            mnu_OPT    = 'NASTA~V~';
            tit_OPT    = 'ZPRACOVèNã óDAJó';


            mnu_SYSTEM = 'S~Y~STêM';
            tit_SYSTEM = 'VLASTNOSTI PROGRAMU';


            mnu_OPTi       = ' NASTA~V~ENã ';
            tit_OPTi       = 'NASTAVENã ZPRACOVèNã';

            mnu_PREHLAD     = ' PûE~H~LED... ';
            mnu_SPRACOVANIE = ' ~Z~PRACOVèNã... ';
            mnu_ZOBRAZENIE  = ' Z~O~BRAZENã... ';
            mnu_DEKODOVANIE = ' ~D~EKïDOVANã... ';
            mnu_EDITOVANIE  = ' ~P~ODènã... ';
            mnu_TLAC        = ' T~I~SK... ';

            mnuPREHLAD     = ' PûE~H~LED ';
            mnuSPRACOVANIE = ' ZPRACOVèNã ';
            mnuDEKODOVANIE = ' DEKïDOVANã ';
            mnuZOBRAZENIE  = ' ZOBRAZENã ';
            mnuTLAC        = ' TISK ';

            mnuKONFIGURACIA = ' KONFI~G~URACE ';
   {$ENDIF}


   {$IFDEF ENGLISH}
     const
            mnu_RPL   = '~R~PL';
            tit_RPL   = 'REPETITIVE FLIGHT PLANS';

            mnu_PLN   = 'PL~N~';
            tit_PLN   = 'FLIGHT CLEARANCES';

            mnu_FPL4  = '~F~PL';
            tit_FPL4  = 'ATS-ROUTE FLIGHT PLANS';

            mnu_FPLM  = '~F~PL';
            tit_FPLM  = 'PLANS OF MILITARY CONTROLLED FLIGHTS';

            mnu_KRL   = '~K~RL';
            tit_RKL   = 'KRãDLA';

            mnu_ZAM   = '~Z~AM';
            tit_ZAM   = 'ZAMESTNANIA LETISKA';

            mnu_QGO   = '~Q~GO';
            tit_QGO   = 'SCHOPNOSÜ LETISKA';

            mnu_DVZ   = '~D~VZ';
            tit_DVZ   = 'DIVERZIE LETãSK';

            mnu_PRZ   = 'PR~Z~';
            tit_PRZ   = 'íIADOSTI O PRIDELENIE PRIESTOROV';

            mnu_PRS   = '~A~SM';
            tit_PRS   = 'USE OF AIRSPACE';

            mnu_SPR   = 'MS~G~';
            tit_SPR   = 'MESSAGES';

            mnu_TLG   = 'T~L~G';
            tit_TLG   = 'TELEGRAMS';


            mnu_MAPA  = 'MA~P~';

            mnu_PLANZET = 'TA~B~LET';
            tit_PLANZET = 'MAP TABLET ADJUSTMENT';


            mnu_NAJDI  = 'FI~N~D';
            tit_NAJDI  = 'FLIGHT DATA PRESENTATION';

            mnu_STREAM = 'I~/~O';
            tit_STREAM = 'INPUT/OUTPUT DATA';

            mnu_UDAJE  = '~D~ATA';
            tit_UDAJE  = 'PLANS, MESSAGES/NOTAMS';


            mnu_MMI    = 'M~M~I';
            tit_MMI    = 'MMI SETTINGS';

            mnu_OPT    = 'O~P~TIONS';
            tit_OPT    = 'DATA PROCESSING';

            mnu_SYSTEM = 'S~Y~STEM';
            tit_SYSTEM = 'PROGRAMM SETTINGS';


            mnu_OPTi        = ' ~O~PTIONS ';
            tit_OPTi        = 'PROCESSING SETTINGS';

            mnu_PREHLAD     = ' ~L~ISTING... ';
            mnu_SPRACOVANIE = ' ~P~ROCESSING... ';
            mnu_ZOBRAZENIE  = ' DISPLA~Y~ING... ';
            mnu_DEKODOVANIE = ' ~D~ECODING... ';
            mnu_EDITOVANIE  = ' ~F~ILLING... ';
            mnu_TLAC        = ' PRIN~T~... ';

            mnuPREHLAD      = ' ~L~ISTING ';
            mnuSPRACOVANIE  = ' PROCESSING ';
            mnuDEKODOVANIE  = ' DECODING ';
            mnuZOBRAZENIE   = ' DISPLAYING ';
            mnuTLAC         = ' PRINTING ';

            mnuKONFIGURACIA = ' KONFI~G~URATION ';
   {$ENDIF}
