{$IFDEF SLOVAK}

 const UZLY       = ' U~Z~LY SIETE... ';

       NSTAT      = ' P~O~SLEDNù STAV UZLOV... ';
        NSTAT_    = 'ZOBRAZENIE STAVU UZLOV';
       NINIT      = ' I~N~ICIALIZèCIA UZLOV... ';
        NINIT_    = 'POVOLENIE INICIALIZèCIE';

       NIVYP      = '~V~YPNUTIE INICIALIZèCIE UZLA ';
       NIINT      = '~I~NTERVAL INICIALIZèCIE UZLA ';
       NIPOCET    = 'POÄET ZLYHANã INICIALIZèCIE ';

{$ENDIF}


{$IFDEF CZECH}

 const UZLY       = ' U~Z~LY SãTE... ';

       NSTAT      = ' P~O~SLEDNã STAV UZL¶... ';
        NSTAT_    = 'ZOBRAZENã STAVU UZL¶';
       NINIT      = ' I~N~ICIALIZACE... ';
        NINIT_    = 'POVOLENã INICIALIZACE';

       NIVYP      = '~V~YPNUTã INICIALIZACE UZLU ';
       NIINT      = '~I~NTERVAL INICIALIZACE UZLU ';
       NIPOCET    = 'POÄET ZLYHANã INICIALIZACE ';

{$ENDIF}


{$IFDEF ENGLISH}

 const UZLY       = ' NETWORK N~O~DES... ';

       NSTAT      = ' LAST NODE ~S~TATUS... ';
        NSTAT_    = 'DISPLAY NODES STATUS';
       NINIT      = ' NODES ~I~NITIALIZATION... ';
        NINIT_    = 'NODES INITIALIZATION';

       NIVYP      = '~D~ISABLING NODE INITIALIZATION ';
       NIINT      = 'INITIALIZATION FAILURE ~I~NTERVAL ';
       NIPOCET    = 'INITIALIZATION FAILURES ~N~UMBER ';

{$ENDIF}
