   {$IFDEF SLOVAK}
     const  STREAM_LISTING   = ' POVOLENIE ~V~ùPISU SPRèV ';
            DATA_DECODING    = ' ~D~EKïDOVANIE PLèNOV/SPRèV ';
            DATA_PROCESSING  = ' ~S~PRACOVANIE PLèNOV/SPRèV ';
            SYSTEM_OPTIONS   = ' ~I~Nê NASTAVENIA ';
   {$ENDIF}


   {$IFDEF CZECH}
     const  STREAM_LISTING   = ' POVOLENã ~V~ùPISU ZPRèV ';
            DATA_DECODING    = ' ~D~EKïDOVANã PLèN¶/ZPRèV ';
            DATA_PROCESSING  = ' ~Z~PRACOVèNã PLèN¶/ZPRèV ';
            SYSTEM_OPTIONS   = ' J~I~Nê NASTAVENã ';
   {$ENDIF}


   {$IFDEF ENGLISH}
     const  STREAM_LISTING   = ' I/O ~S~TREAM SCROLLING ';
            DATA_DECODING    = ' ~D~ECODING OF PLANs/MESSAGEs ';
            DATA_PROCESSING  = ' ~P~ROCESSING OF PLANs/MESSAGEs ';
            SYSTEM_OPTIONS   = ' ~O~THER SETTINGs ';
   {$ENDIF}

