{$IFDEF SLOVAK}

 const MAPY_M     = ' ~M~APY... ';
        MAPY_M_   = 'MAPA';

       ROZSAH_V   = ' ~R~OZSAH/VYSTREDENIE...       ';
        ROZSAH    = ' ~R~OZSAH     Alt+7 ';
        PRIESTOR  = ' ~P~RIESTOR   Alt+8 ';
        VYSTRED   = ' ~V~YSTREÖ    Alt+9 ';
        CENTRUJ   = ' ~C~ENTRUJ    Alt+0 ';

       KRESLENIE  = ' ~K~RESLENIE CIEäOV...         ';
       KRESLENIE_ = 'KRESLENIE CIEäOV';
        KRES_C    = '~C~IVILNê CIELE' ;
        KRES_M    = '~V~OJENSKê CIELE';
        KRES_O    = '~I~Nê CIELE';
        KRES_SSR  = 'ZOBRAZENIE ~S~SR';
        KRES_TB   = '~T~YP BODOV';
        KRES_PB   = '~P~OPIS BODOV';
        KRES_8x8  = '~8~x8 FONT';

{$ENDIF}


{$IFDEF CZECH}

 const MAPY_M     = ' ~M~APY... ';
        MAPY_M_   = 'MAPA';

       ROZSAH_V   = ' ~R~OZSAH/VYSTûEDâNã...        ';
        ROZSAH    = ' ~R~OZSAH    Alt+7 ';
        PRIESTOR  = ' ~P~ROSTOR   Alt+8 ';
        VYSTRED   = ' ~V~YSTûEÖ   Alt+9 ';
        CENTRUJ   = ' ~C~ENTRUJ   Alt+0 ';

       KRESLENIE  = ' ~K~RESLENã CãL¶...            ';
       KRESLENIE_ = 'KRESLENã CãL¶';
        KRES_C    = '~C~IVILNã CãLE' ;
        KRES_M    = '~V~OJENSKê CãLE';
        KRES_O    = 'J~I~Nê CãLE';
        KRES_SSR  = 'ZOBRAZENã ~S~SR';
        KRES_TB   = '~T~YP BOD¶';
        KRES_PB   = '~P~OPIS BOD¶';
        KRES_8x8  = '~8~x8 FONT';

{$ENDIF}


{$IFDEF ENGLISH}

 const MAPY_M     = ' ~M~APS... ';
        MAPY_M_   = 'MAP';

       ROZSAH_V   = ' ~R~ANGE/CENTERING... ';
        ROZSAH    = ' ~R~ANGE      Alt+7 ';
        PRIESTOR  = ' ~A~REA       Alt+8 ';
        VYSTRED   = ' ~M~OVING     Alt+9 ';
        CENTRUJ   = ' ~C~ENTERING  Alt+0 ';

       KRESLENIE  = ' ~T~ARGETs DRAWING... ';
       KRESLENIE_ = 'TARGETs DRAWING';
        KRES_C    = '~C~IVILIAN FLIGHTs' ;
        KRES_M    = '~M~ILITARY FLIGHTs';
        KRES_O    = '~O~THER FLIGHTs';
        KRES_SSR  = '~S~SR DISLAYING';
        KRES_TB   = 'POINTS ~T~YPE';
        KRES_PB   = 'POINTS ~D~ESRIPTION';
        KRES_8x8  = '~8~x8 FONT';

{$ENDIF}
