   {$IFDEF SLOVAK}
   {$ENDIF}

   {$IFDEF CZECH}
   {$ENDIF}

   {$IFDEF ENGLISH}

    const   PLNM              = ' PL~N~ FLIGHT CLEARANCEs ';

            PLN_MAKE          = ' ~P~ROCESS PLN PLANs ';


            PLNPEND           = 'PEND PLN PROCESSING';
            PLNADR            = 'CHECK PLN SOURCE ADDRESS';
            PLNFPL            = 'CHECK PLN REGULARITY';
            PLNERR            = 'EVALUATE ERROR AS ERR/TLG';

            PLNA36YKA         = 'DATA IN CYRILLIC';

            FPL4APROVEDDISPLAY = 'INDICATE FLIGHT CLEARANCE IN FPL';
            FPL4APROVEDCHECK   = 'CHECK ACTIVATED FLIGHT CLEARANCE';
            {FPL4APROVEDBYFDA   = 'FLIGHT APPROVED WHEN FDA EDITING';}
   {$ENDIF}
