      const ctrlPRS = '   Ctrl+F7 ';

      {$IFDEF SLOVAK}

        const mnu_PRS_PLAN    = ' PLèN VYUíITIA ~P~RIESTORU... ';
              mnu_PRS_PLAN_F7 = ' PLèN VYUíITIA ~P~RIESTORU  F7 ';
              mnu__UP_PLAN    = ' PODANIE SPRèVY AUP~/~UUP... ';

              titPRS_PLANY    = 'PLèNY VYUíITIA PRIESTOROV';
              PRS_ACT         = ' VYUíãVANê PRIESTORY';
              PRS_ARR         = ' UVOúNENê PRIESTORY';

              PRS_PLANY       = ' ~P~LèNY VYUíITIA PRIESTOROV ';


              PRSM            = ' PLèNY VYUíITIA VZDUõNêHO ~P~RIESTORU ';

              PRSACC          = 'HLèSENIE O SCHVèLENã PODANêHO PLèNU ';
              PRSUSE          = 'HLèSENIA O VYUíãVANã PRIESTOROV';
              PRSMAP          = 'UPOZORNENIE NA NENèJDENó MAPU' { PRIESTORU '};
              PRSFLR          = 'KONTROLA VùõKOVEJ REGULARITY PRIESTOROV';
              PRSPRE          = 'PREAKTIVOVANIE PLèNOV PRIESTOROV';
              PRSCNL          = 'ZRUõENIE NEAKTIVOVANùCH PLèNOV';
              PRSDEL          = 'DEAKTIVOVANIE PLèNOV';


              PRSL            = 'VOLITEúNè VEúKOSÜ PLèNU PRIESTORU';
              PRSL18          = '- POÄET RIADKOV V POLI "POZNèMKA" ';
              PRSSTRIP        = '(PRE)AKTIVOVANê PLèNY AKO STRIPY';
      {$ENDIF}


      {$IFDEF CZECH}

        const mnu_PRS_PLAN    = ' PLèN VYUíITã ~P~ROSTORU... ';
              mnu_PRS_PLAN_F7 = ' PLèN VYUíITã ~P~ROSTORU         F7 ';
              mnu_AUP_PLAN    = ' PODèNã ZPRèVY AUP~/~UUP... ';

              titPRS_PLANY    =  'PLèNY VYUíITã PROSTOR¶';
              PRS_ACT         = ' AKTIVOVANê PROSTORY';
              PRS_ARR         = ' UVOLNâNê PROSTORY';

              PRS_PLANY       =  ' ~P~LèNY VYUíITã PROSTOR¶ ';


              PRSM            = ' PLèNY VYUíITã VZDUõNêHO ~P~ROSTORU ';

              PRSACC          = 'HLèõENã O SCHVèLENã PODANêHO PLèNU ';
              PRSUSE          = 'HLèõENã O VYUíãVANã PROSTOR¶';
              PRSMAP          = 'UPOZORNâNã NA NENALEZENOU MAPU PROSTORU ';
              PRSFLR          = 'KONTROLA VùõKOVê REGULARITY PROSTOR¶';
              PRSPRE          = 'PûEAKTIVOVèNã SCHVèLENùCH PLèN¶';
              PRSCNL          = 'ZRUõENã NEAKTIVOVANùCH PLèN¶';
              PRSDEL          = 'DEAKTIVOVèNã PLèN¶';


              PRSL            = 'VOLITELNè VELIKOST PLèNU PROSTORU';
              PRSL18          = '- POÄET ûèDKU V POLI "POZNèMKA" ';
              PRSSTRIP        = '(PûE)AKTIVOVèNY PLèNY JAKO STRIPY';
      {$ENDIF}


      {$IFDEF ENGLISH}
        const mnu_PRS_PLAN    = ' ~A~REA USE PLAN... ';
              mnu_PRS_PLAN_F7 = ' ~A~REA USE PLAN   F7 ';
              mnu_AUP_PLAN    = ' PODANIE SPRèVY AUP~/~UUP... ';

              titPRS_PLANY    =  'AIRSPACE USE PLANs';
              PRS_ACT         = ' ACTIVATED AREAs';
              PRS_ARR         = ' RELEASED AREAs';

              PRS_PLANY       =  ' ~A~IRSPACE USE PLANs ';


              PRSM            = ' ~A~IRSPACE USE PLANs ';

              PRSACC          = 'APPROVING AREA PLAN REPORTS ';
              PRSUSE          = 'AREA USE REPORTS ';
              PRSMAP          = 'NOT FOUND AREA MAP WARNING ';
              PRSFLR          = 'ALTITUDE REGULARITY WARNING ';
              PRSPRE          = 'APPROVED PLAN PREACTIVATION';
              PRSCNL          = 'NOT USED PLAN DEACTIVATION';
              PRSDEL          = 'PLAN DEACTIVATION';


              PRSL            = 'ADJUSTABLE AREA PLAN SIZE IN LISTING';
              PRSL18          = '- NUMBER OF LINES IN FIELD "NOTE" ';
              PRSSTRIP        = 'DISPLAY (PRE)ACTIVATED PLAN AS STRIP';
      {$ENDIF}
