      {$IFDEF SLOVAK}

        const PRZPLAN         = ' íI~A~DOSÜ O PRIDELENIE PRIESTORU ';

              PRZ_PLAN        = ' ~í~IADOSTI O PRIDELENIE PRIESTOROV ';
              PRZ_PLANY       = ' í~I~ADOSTI O PRIDELENIE PRIESTOROV ';

              PRZ_VLIS        = ' VYDANê NARAIDENIA VLIS ';
              PRZ_VLIS_NAR    = ' NARIADENIE V~L~IS PRE PRIDELENIE VZDUõNêHO PRIESTORU ';
              PRZ_VLIS_NOTAM  = ' ~N~OTAMY VLIS O PRIDELENã VZDUõNêHO PRIESTORU ';

              PRZM            = PRZ_PLANY;

              PRNT1           = 'VOLITEúNè VEúKOSÜ NOTAMU V ZOZNAME';
              {PRNT2           = 'A íIADOSTI O PRIDELENIE PRIESTORU : ';}
              PRNLD           = '- POÄET RIADKOV V POLI "ÄASOVê ROZPéTIE"';
              PRNLE           = '- POÄET RIADKOV V POLI "TEXT NOTAMU"';

      {$ENDIF}


      {$IFDEF CZECH}

        const PRZPLAN         = ' í~è~DOST O PûIDâLENã PROSTORU ';

              PRZ_PLANY       = ' ~í~IADOSTI O PRIDELENIE PRIESTOROV ';
              PRZM            = PRZ_PLANY;

              PRNT1           = 'VOLITELNè VELIKOST NOTAMU V SEZNAMU';
              {PRNT2           = '  A íèDOSTI O PûIDâLENã PROSTORU : ';}
              PRNLD           = '- POÄET ûèDKU V POLI "ÄASOVê ROZPâTã"';
              PRNLE           = '- POÄET ûèDKU V POLI "TEXT NOTAMU"';
      {$ENDIF}


      {$IFDEF ENGLISH}
        const PRZPLAN         = ' í~I~ADOSÜ O PRIDELENIE PRIESTORU ';

              PRZ_PLANY       = ' ~í~IADOSTI O PRIDELENIE PRIESTOROV ';
              PRZM            = PRZ_PLANY;

              PRNT1           = 'VOLITEúNè VEúKOSÜ NOTAMU ';
              {PRNT2           = '  A íIADOSTI O PRIDELENIE PRIESTORU : ';}
              PRNLD           = '- POÄET RIADKOV V POLI "ÄASOVê ROZPéTIE"';
              PRNLE           = '- POÄET RIADKOV V POLI "TEXT NOTAMU"';
      {$ENDIF}
