      {$IFDEF SLOVAK}
        const  mnu_QGO_PLAN  = ' HLèSENIA O S~T~AVE LETISKA... ';
               {PrQGO    = ' HLèSENIA O ~S~TAVE LETãSK ';}

               QGOPLAN       = ' HLèSENIE O ~S~TAVE LETISKA  F8 ';
               QGOCHG        = ' ~A~KTUALIZèCIA HLèSENIA ';
               QGOCNL        = ' ~Z~RUõENIE HLèSENIA ';
               QGOPREHLAD    = ' ~H~LèSENIA O STAVE LETãSK  Ctrl+F8 ';
               QGOPPL        = ' ~P~RIPRAVENê HLèSENIA ';
               QGOARCH       = ' ARCH~I~VOVANê HLèSENIA ';

               QGOM          = ' ~S~TAV/SCHOPNOSTI LETãSK ';
               QGOREP        = 'HLèSENIE O ZMENE STAVU/SCHOPNOST° ';
               QGOVAR        = 'UPOZORNENIE NA HLèSENIE -//- ';

      {$ENDIF}


      {$IFDEF CZECH}
        const  QGOM          = ' ~S~TAV/SCHOPNOSTI LETIõÜ ';
               QGOREP        = 'HLèõENã O ZMâNE STAVU/SCHOPNOSTI ';
               QGOVAR        = 'UPOZORNâNã NA HLèõENã -//- ';

      {$ENDIF}