   {$IFDEF SLOVAK}
   {$ENDIF}

   {$IFDEF CZECH}
   {$ENDIF}

   {$IFDEF ENGLISH}
    const   RPLM              = ' ~R~PL  REPETIVE PLANs ';

            mnu_RPL_PLAN      = 'RPL  REPETIVE PLAN...';
            mnu_RPL_F2        = ' RPL ~F~ILLING            (F2) ';
            mnu_RPL_CHG       = ' RPL ~C~ORRECTION ';
            mnu_RPL_BRK       = ' RPL ~D~EACTIVATION ';
            mnu_RPL_CNT       = ' RPL ~R~EACTIVATION ';

            mnu_RPL_UPDATE    = ' U~P~DATE RPL DATABASE... ';
            tit_RPL_UPDATE    = ' RPL DATABASE UPDATING ';
            mnu_RPL_ERRORS_   = ' L~A~ST UPDATING RESULTS ';
            mnu_RPL_UPDATE_   = ' CONTINUE IN U~P~DATING ';
            mnu_RPL_CORRECT_  = ' ERRORS ~C~ORRECTION ';
            mnu_RPL_ADD       = ' E~X~TEND DATABASE ';
            mnu_RPL_REPLACE   = ' R~E~PLACE DATABASE ';
            mnu_RPL_RESTORE   = ' RE~S~TORE DATABASE ';

            mnu_FPL_MAKE      = ' FPL ~I~NITIALIZATION ';
            mnu_RPL_MAKE      = ' MAK~E~ DAY FPLs ';
            mnu_RPL_MAKE_     = ' FINIS~H~ DAY FPLs ';


            RPLERR            = 'DISPLAY RPL ERROR';
            RPLAS15           = 'ROUTE ASSIGNMENT ';
            RPLPEND           = 'PEND RPL PROCESSING';
            RPLHOUR           = 'HOUR OF RPL PROCESSING';
            RPLMIN            = 'MIN OF RPL PROCESSING';

            RPLL15            = '- NUMBER OF LINES IN FIELD 15 ';
            RPLL18            = '- NUMBER OF LINES IN FIELD 18 ';

            RPLA36YKA         = 'DATA IN CYRILLIC ';

            RPLPRNIFPS        = 'IFPS/DOC.4444 PRINT FORM ';
   {$ENDIF}
