 {$IFDEF SLOVAK}
  const   mnufrm_VLOZIT_TRAT = 'Vloëiü';
          mnufrm_TRAT        = 'k¢d trate';
          mnufrm_BODY        = 'body trate';

          mnufrm_SMER_LETU   = 'Smer trate';
          mnufrm_TRAT_SMER   = 'v uvedenom smere';
          mnufrm_TRAT_OPAK   = 'v opaánom smere';

 {$ENDIF}

 {$IFDEF CZECH}
  const   mnufrm_VLOZIT_TRAT = 'Vloëit';
          mnufrm_TRAT        = 'k¢d tratà';
          mnufrm_BODY        = 'body tratà';

          mnufrm_SMER_LETU   = 'Smer tratà';
          mnufrm_TRAT_SMER   = 'v uvedenom smere';
          mnufrm_TRAT_OPAK   = 'v opaánom smere';
 {$ENDIF}

 {$IFDEF ENGLISH}
  const   mnufrm_VLOZIT_TRAT = 'Insert';
          mnufrm_TRAT        = 'route code';
          mnufrm_BODY        = 'route points';

          mnufrm_SMER_LETU   = 'Route direction';
          mnufrm_TRAT_SMER   = 'in the given direction';
          mnufrm_TRAT_OPAK   = 'in the oppositte direction';
 {$ENDIF}