      {$IFDEF SLOVAK}

       const  SPRSPR    = ' ~S~PRèVA                 F10 ';
              SPRTLG    = ' ~T~ELEGRAM ';

              SPRM      = ' DORUÄENê SPRèV~Y~ ' {NEFORMALIZOVANê SPRèVY/~T~ELEGRAMY '};
              SPRVAR    = ' ZVUKOVè SIGNALIZèCIA DORUÄENIA SPRèVY ';
              SPRLIM    = ' LIMIT NA POTVRDENIE PREVZATIA SPRèVY';
              SPRSAVE   = ' ODLOíENIE NEPREVZATùCH SPRèV';
              SPRREP    = ' OZNèMENIE O DORUÄENã SPRèVY ';

              SPRL      = 'VOLITEúNè VEúKOSÜ SPRèVY/TELEGRAMU';
              SPRLA     = '-POÄET RIADKOV V POLI "ADRESA" ';
              SPRLT     = '-POÄET RIADKOV V POLI "TEXT" ';

              SPRD      = ' ~D~ORUÄENê SPRèVY    Alt+F10 ';
              SPRO      = ' ~O~DOSLANê SPRèVY   Ctrl+F10 ';
              SPRV      = ' V~õ~ETKY SPRèVY    Shift+F10 ';
              SPRA      = ' ~A~RCHãV...          ';
               SPRA_    = 'ARCHãV SPRèV';
              SPRDA     = ' ~D~ORUÄENê SPRèVY ';
              SPROA     = ' ~O~DOSLANê SPRèVY ';
              SPRVA     = ' V~õ~ETKY   SPRèVY ';
      {$ENDIF}


      {$IFDEF CZECH}

       const  SPRSPR    = ' ~S~PRèVA                 F10 ';
              SPRTLG    = ' ~T~ELEGRAM ';

              SPRM      = ' DORUÄENê SPRèV~Y~ '{' NEFORMALIZOVANê ZPRèVY/~T~ELEGRAMY '};
              SPRVAR    = ' ZVUKOVè SIGNALIZACE DORUÄENã ZPRèVY ';
              SPRLIM    = ' LIMIT NA POTVRZENã PûREVZETã ZPRèVY';
              SPRSAVE   = ' ODLOíENã NEPûEVZATùCH ZPRèV';
              SPRREP    = ' OZNèMENã O DORUÄENã ZPRèVY ';

              SPRL      = 'VOLITELNè VELIKOST ZPRèVY/TELEGRAMU ';
              SPRLA     = '-POÄET ûèDKU V POLI "ADRESA" ';
              SPRLT     = '-POÄET ûèDKU V POLI "TEXT"  ';

              SPRD      = ' ~D~ORUÄENê SPRèVY    Alt+F10 ';
              SPRO      = ' ~O~DOSLANê SPRèVY   Ctrl+F10 ';
              SPRV      = ' ~V~õETKY SPRèVY    Shift+F10 ';
              SPRA      = ' ~A~RCHãV...          ';
               SPRA_    = 'ARCHãV SPRèV';
              SPRDA     = ' ~D~ORUÄENê SPRèVY ';
              SPROA     = ' ~O~DOSLANê SPRèVY ';
              SPRVA     = ' ~V~õETKY   SPRèVY ';
      {$ENDIF}


      {$IFDEF ENGLISH}

       const  SPRSPR    = ' ~M~ESSAGE                F10 ';
              SPRTLG    = ' ~T~ELEGRAMM MESSAGE ';

              SPRM      = ' LETVIS ~M~ESSAGES ';
              SPRVAR    = ' ALARM WHEN RECEIVED MESSAGE ';
              SPRLIM    = ' MESSAGE CONFIRM';
              SPRSAVE   = ' SAVE NOT CONFIRMED MESSAGES';
              SPRREP    = ' MESSAGE DELIVERING REPORT ';

              SPRL      = 'ADJUSTABLE MESSAGE SIZE IN LISTING ';
              SPRLA     = '- NUMBER OF LINES IN FIELD "ADDRESS" ';
              SPRLT     = '- NUMBER OF LINES IN FIELD "TEXT"  ';

              SPRD      = ' ~R~ECEIVED MESSAGES  Alt+F10 ';
              SPRO      = ' ~S~ENDED MESSAGES   Ctrl+F10 ';
              SPRV      = ' ~A~LL MESSAGES     Shift+F10 ';
              SPRA      = ' ~A~RCHIV...          ';
               SPRA_    = 'MESSAGES ARCHIV';
              SPRDA     = ' ~R~ECEIVED MESSAGES ';
              SPROA     = ' ~S~ENDED MESSAGES ';
              SPRVA     = ' ~A~LL MESSAGES ';
      {$ENDIF}
