   {$IFDEF SLOVAK}
   {$ENDIF}

   {$IFDEF CZECH}
   {$ENDIF}

   {$IFDEF ENGLISH}
    const   SSRM            = ' ~S~SR MANAGEMENT ';

            SSRCHECK        = 'SSR CODE MANAGEMENT ';
            SSRNEXTUSE      = 'SSR CODE ALOCATION LIMIT CHECK';
            SSRNEXTUSELIMIT = 'SSR CODE ALOCATION LIMIT';

            {SSRASSIGN       = 'SSR CODE ASSIGNING';}
            {SSRLIST         = 'SSR CODE SELECTION/ASSIGNING';}
            {SSRNOTCFG      = 'NOT CONFIGURED CODES ENABLED';}
   {$ENDIF}


