   {$IFDEF SLOVAK}
    const mnu_EST    = 'ES~T~';
          tit_EST    = ' PODANIE STRIPU PRE';
           F4e       = ' ~C~IVILNù LET        (F4) ';
           F5e       = ' ~V~OJENSKù/INù LET   (F5) ';

          mnu_ETO    = 'ET~O~';
          tit_ETO    = 'OPRAVA £UDAJOV PRE';
           F4o       = ' ~C~IVILNù LET    ';
           F5o       = ' ~V~OJENSKù LET   ';
           F6o       = ' ~I~Nù LET        ';

          mnu_DEL    = 'DE~L~';
          tit_DEL    = 'ZMAZANIE STRIPU ';
           PA        = ' ~P~REVZATIE VõETKùCH NAVRHOVANùCH    (Alt+Ins) ';
           PD        = ' ~Z~AMIETNUTIE VõETKùCH NAVRHOVANùCH  (Alt+Del) ';
           F4c       = ' ~C~IVILNù LET  ';
           F5c       = ' ~V~OJENSKù LET ';
           F6c       = ' ~I~Nù LET      ';
           DELa      = ' ZM~A~ZANIE VõETKùCH STRIPOV ';
   {$ENDIF}


   {$IFDEF CZECH}
    const mnu_EST    = 'ES~T~';
          tit_EST    = ' PODèNã STRIPU PRO';
           F4e       = ' ~C~IVILNã LET        (F4) ';
           F5e       = ' ~V~OJENSKù/JINù LET  (F5) ';

          mnu_ETO    = 'ET~O~';
          tit_ETO    = 'OPRAVA £UDAJ¶ PRO';
           F4o       = ' ~C~IVILNã LET    ';
           F5o       = ' ~V~OJENSKù LET   ';
           F6o       = ' J~I~Nù LET       ';

          mnu_DEL    = 'DE~L~';
          tit_DEL    = 'ZMAZèNã STRIPU';
           PA        = ' ~P~ûEVZETã VõECH NAVRHOVANùCH   (Alt+Ins) ';
           PD        = ' ~Z~AMãTNUTã VõECH NAVRHOVANùCH  (Alt+Del) ';
           F4c       = ' ~C~IVILNã LET  ';
           F5c       = ' ~V~OJENSKù LET ';
           F6c       = ' J~I~Nù LET     ';
           DELa      = ' ZM~A~ZèNã V~õ~ECH STRIP¶   ';
   {$ENDIF}


   {$IFDEF ENGLISH}
    const mnu_EST    = 'ES~T~';
          tit_EST    = ' ESTIMATED TIME MESSAGE ';
           F4e       = ' ~C~IVILIAN FLIGHT       (F4) ';
           F5e       = ' ~M~ILITARY/OTHER FLIGHT (F5) ';

          mnu_ETO    = 'ET~O~';
          tit_ETO    = ' ESTIMATED TIME CORRECTION ';
           F4o       = ' ~C~IVILIAN FLIGHT  ';
           F5o       = ' ~M~ILITARY FLIGHT  ';
           F6o       = ' ~O~THER FLIGHT     ';

          mnu_DEL    = 'DE~L~';
          tit_DEL    = ' STRIP DELETE ';
           PA        = ' ~A~CCEPT ALL PROPOSED STRIPS    (Alt+Ins) ';
           PD        = ' ~D~ECLINE ALL PROPOSED STRIPS   (Alt+Del) ';
           F4c       = ' ~C~IVILIAN FLIGHT ';
           F5c       = ' ~M~ILITARY FLIGHT ';
           F6c       = ' ~O~THER FLIGHT ';
           DELa      = ' DE~L~ETE ALL STRIPS ';
   {$ENDIF}
