{$IFDEF SLOVAK}

 const UTC        = ' NASTAVENIE ~H~ODãN... ';
        UTC_      = 'NASTAVENIE HODãN';
        I_UTC     = 'ÄASOVè ~S~YNCHRONIZèCIA ';
        M_UTC     = 'ÄASOVê ~Z~NAMENIE ';
        C_UTC     = ' ~U~TC ';

       TLAC       = ' NASTAVENIE ~T~LAÄIARNE... ';
        TLAC_     = '~N~ASTAVENIE TLAÄIARNE';
        TL_OFF    = '~P~OSUN ZAÄIATKU STRèNKY';
        TL_TEST   = '~T~EST TLAÄIARNE';
        TL_NET    = 'TLAÄ CEZ ~L~AN';

       I_NAST     = ' ~I~Nê NASTAVENIA... ';
        I_SIM     = 'SIMULèTOR PRE UNIX/DOS';
        I_NAST_   = 'INê NASTAVENIA';
        I_REPR    = '~R~EPRODUKTOR ';
        {I_SAVECFG = 'UKLADANIE NASTAVENã ~A~PLIKèCIE ';
        I_SAVEMAP = 'UKLADANIE NASTAVENã ~M~èP ';}


 const  HELPINDEX  = ' ~H~ELP INDEX       Shift+F1 ';
        VERSION    = ' ~V~ERZIA PROGRAMU ';
        UPGRADE    = ' ~Z~MENY V PROGRAME  ';

        EXT        = ' U~K~ONÄENIE PROGRAMU  Alt+X ';

{$ENDIF}


{$IFDEF CZECH}

 const UTC        = ' NASTAVENã ~H~ODIN... ';
        UTC_      = 'NASTAVENã HODIN';
        I_UTC     = 'ÄASOVè ~S~YNCHRONIZACE ';
        M_UTC     = 'ÄASOVê ZNAMENã ';
        C_UTC     = ' ~U~TC ';

       TLAC       = ' NASTAVENã ~T~ISKèRNY... ';
        TLAC_     = 'NASTAVENã TISKèRNY';
        TL_OFF    = '~P~OSUN ZAÄèTKU STRèNKY';
        TL_TEST   = '~T~EST TISKèRNY';
        TL_NET    = 'TISK PûES ~L~AN';

       I_NAST     = ' J~I~Nê NASTAVENã... ';
        I_SIM     = 'SIMULèTOR PRE UNIX/DOS';
        I_NAST_   = 'NASTAVENã';
        I_REPR    = 'REPRODUKTOR ';
        {I_SAVECFG = 'UKLADèNã NASTAVENã ~A~PLIKACE ';
        I_SAVEMAP = 'UKLADèNã NASTAVENã ~M~AP ';}


 const  HELPINDEX  = ' ~H~ELP INDEX       Shift+F1 ';
        VERSION    = ' ~V~ERZE PROGRAMU ';
        UPGRADE    = ' ~Z~MâNY V PROGRAMU ';

        EXT        = ' U~K~ONÄENã PROGRAMU   Alt+X ';

{$ENDIF}


{$IFDEF ENGLISH}

 const UTC        = ' ~C~LOCK ADJUSTMENT... ';
        UTC_      = 'CLOCK ADJUSTMENT ';
        I_UTC     = 'TIME ~S~YNCHRONISE ';
        M_UTC     = 'TIME ~M~ARKER ';
        C_UTC     = ' ~U~TC ';

       TLAC       = ' ~P~RINTER ADJUSTMENT... ';
        TLAC_     = '~P~RINTER ADJUSTMENT';
        TL_OFF    = 'PAGE ~O~FFSET';
        TL_TEST   = 'PRINTER ~T~EST';
        TL_NET    = 'PRINT VIA ~L~AN';

       I_NAST     = ' ~O~THER ADJUSTMENTS... ';
        I_NAST_   = 'OTHER ADJUSTMENTS';
        I_SIM     = 'SIMULATOR FOR UNIX/DOS';
        I_REPR    = '~B~EEPING ON/OFF ';
        {I_SAVECFG = 'UKLADANIE NASTAVENã ~A~PLIKèCIE ';
        I_SAVEMAP = 'UKLADANIE NASTAVENã ~M~èP ';}


 const  HELPINDEX  = ' ~H~ELP INDEX    Shift+F1 ';
        VERSION    = ' PROGRAMM ~V~ERSION ';
        UPGRADE    = ' PROGRAMM ~U~DATING ';

        EXT        = ' E~X~IT             Alt+X ';

{$ENDIF}

