 AA =
 AA =
 AA =
 AA =

 ? AMC = LZBBZDZX

 FUA = EBBDCEUW           ; CFMU/CADF Brusel

 FUA = LKPRZDXZ           ; AMC Praha
 FUA = LZBBZQXZ LZBBZFZX  ; ACC/FIC Bratislava
 FUA = LZIBYWYX           ; SRLP Bratislava

 FUA = LZIBZTZX           ; RLP Bratislava
 FUA = LZKXZTZX           ; RLP Kosice
 FUA = LZPPZTZX           ; RLP Piestany
 FUA = LZTTZTZX           ; RLP Tatry
 FUA = LZZIZTZX           ; RLP Zilina


; ---------------------------------------
; Casove limity
;
; ---------------------------------------

 FUA -24H = disabled;  Planovanie priesorov je ohranicene limitmi 24/6 hodin vopred
 FUA -1H  = enabled;   Vynimky, ktore nemusia byt planovane a schvalovane 24 hodin vopred

 LIMIT FUA -1H = 60;

 -1H = TSA06
;-1H = TSA06B
;-1H = TSA06C

