; -------------------------------------------
; config pre LAN - IPX  ( 600 )
; -------------------------------------------
;
; -------------------------------------------
; nazov    uzol              
; -------------------------------------------

  OPL    ; 1B2698DD = 1 ; @THIS @BRIDGE
  METEOR ; C0564665 = 2 ;
