;-----------------------
; FIR DESCRIBTION
;תתתתתתתתתתתתתתתתתתתתתתת

 AIRBASE = 100


;-----------------------
; SSR MANAGEMENT
;תתתתתתתתתתתתתתתתתתתתתתת

; SSR = 6116-6130


;-----------------------
; FUNCTIONS
;תתתתתתתתתתתתתתתתתתתתתתת

 edit FPLm = yes ; povolenie editacie vojenskeho a ineho stripu
 edit FPLc = yes ; povolenie editacie civilneho stripu


;-----------------------
; SYSTEM
;תתתתתתתתתתתתתתתתתתתתתתת

 time = 1
 db-rw-close = no


exception-call-desc = false