; -----------------------------------------
; -----------------------------------------
; FDP/EDD  - SRLP Bratislava
; -----------------------------------------

; --------------------------------------------------------------------------------------------------------------------------------
; Pracovisko ; Adresa logicka,   RTR, IP        ; Protokol ; Stanica  ; informacie                               ; ine nastavenia
; --------------------------------------------------------------------------------------------------------------------------------

; ----------------------------
; SRLP
; ----------------------------

  BRIDGE     ; StrRLP BRIDGE ,    192.100.141.31 ; ~UDP  L  ; @BRIDGE  ; -heartbeat  MSG
  S-RTZ      ; StrRLP S1     ,    192.100.141.32 ; ~UDP  L  ; @SERVER  ; -master     MSG  ALL  ; timeout=3
  S-ACC      ; StrRLP S2     ,    192.100.141.33 ; ~UDP  L  ; @BSERVER ; -backup     MSG  ALL  ; timeout=3

  EDD        ; StrRLP EDD    ,$08,192.100.141.40 ; @THIS

  TEREN      ; StrRLP TEREN  ,$03,192.100.141.16 ; ~UDP     ; @RDP     ; -slave ALL  @SECTOR
  SOD        ; StrRLP SOD    ,$05,192.100.141.17 ; ~UDP     ; @RDP     ; -slave ALL

  ADP        ; StrRLP TS     ,$06,192.100.141.18 ; ~UDP     ; @RDP     ; -slave ALL
  SAR        ; StrRLP SAR    ,$04,192.100.143.16 ; ~UDP     ; @RDP     ; -slave ALL


; ----------------------------
; PVO
; ----------------------------
  DPVL       ; VS DPVL       ,    192.100.000.33 ; ~UDP ~L  ; @IDD     ; -heartbeat MSG        ; timeout=5
