;-----------------------
; FIR DESCRIBTION
;תתתתתתתתתתתתתתתתתתתתתתת

  FDP REGION           = UKBB  ; nazov regionu (FIR,SEKTOR), v ktorom sa spracovavaju data
  AIRBASE              = UKKK  ; oznacenie letiska, ak nie je v nazve uzla - IDD

  SECTOR               = \FDPÿDATA\MAPS\UK\SECTORS.ACC  ; ekvivalentny prikaz konfiguracneho subora sectors.ini

  FL LOW                       ; ktora je spodna letova hladina ?
  FL VFR                       ; max vyska VFR letu



;-----------------------
; SSR MANAGEMENT
;תתתתתתתתתתתתתתתתתתתתתתת

  SSR = 6116-6130            ; rozsah alokovanych kodov SSR


;-----------------------
; FDP OPTIONS
;תתתתתתתתתתתתתתתתתתתתתתת

; REQ limit                  ; limit na vyziadanie pripomienky k letu (OPL)
; DEP limit                  ; limit na vydanie spravy o strate       (OPL)

  edit FPLM            = yes ; povolenie editacie vojenskeho a ineho stripu
  edit FPLC            = yes ; povolenie editacie civilneho stripu


  FPLO                 = yes ; odlisenie inych vojenskych planov
  FPLO-9               = yes ;   - podla letiska statu/pristatia
  FPLO-AP              = yes ;   - podla typu

  FPLM-AREA            = LZ  ; nazov mapy urcujucej hranice oblasti pre lety vojenskych lietadiel


  estimate ARR         = yes ; prepocet casu pristatia prijateho civilneho stripu,
                             ; ak to je vo FIR;
                             ; plati pre server pri prijme od externej linky
                             ; a pracovne stanice pri podani stripu
  search in FPLC archive     ; kolko archivivanych hodin sa prehladava v archive na EDD ?

  RDP INIT DB          = no  ; inicializacia RDP i datami zo suborov - kontrola na odmazane...

  target refresh             ; interval obnovenia pozicii cielov
  radius map ZAM             ; polomer vykreslenych map



;---------------------------------------------------------------
; nastavenie systemovych premennych, implicitna hodnota je v []
;תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת

  dir.tmp   =                ; docasny narodny adresar
  win.tmp   =                ; adresar pre ukladanie okien (RAM disk)
  win-mem   = no             ; ukladat okna do pamate [NO]

  mouse ver = 6.0            ; ak (starsia) verzia drivera

  menu scroll by mouse = no  ; pohybuje mys riadkom menu ?
  menu palette = 1           ; >0 podsvieteny riadok menu

  time      = 3              ; povolena tolerancia casu (sec)
  font8x8   = rus8x8.FNT     ; subor s fontom pre BGI grafiku, max. 20 znakov

  common archiv = no         ; spolocny subor pre vsetky I/O pkt


;-------------------------------
; nastavenie parametrov siete
;תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת

  NET SEND WAIT        =     ; delay po odoslani spravy do NET
  NET TEST TIMEOUT     = 40  ; test ma stranicu SLAVE po 40 sec
  NET ACK TIMEOUT      = 10  ; cakanie na potvrdenie
  NET ACK ALL          = yes ; implictne

  NET HEARTBEAT              ;  -//- NET
  IPX HEARTBEAT              ; testovanie stavu IPX v protokole IPX0 (BRIDGE OPL)

  NET BUFFERS
  IPX BUFFERS
  RTR BUFFERS

  DAR ARCHIVE          = enabled;
  DAR BUFFERS                ; 30< <300

  IPX_GLOBAL_INIT      = OFF

  IPX REPEAT                 ; opakovanie vyslania spravy v protokole IPX0, ak nebola potvrdena IPX-om

  NET IS INITIALIZED    = OFF ; hlasenie o tom...

  NODE FILTER             = OFF ; povolenie prijimat len od stanic uvedenych v USERs.cfg
  NODE INITIALIZE         = ON  ; je uzol inicializovany po prihlaseni sa ?
  NODE INITIALIZE WAIT    = OFF ; pri inicializacii caka na potvrdenie od uzla, kym vysle dalsiu spravu
  NODE INITIALIZE ALL     = ON  ; FDP uzol sa inicializuje vsetkymi, i uz potvrdenymi datami


;-------------------------------
; archivacia
;תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת

  ARCHIVE NET   =               ; archivovanie paketov     
  ARCHIVE OPL   =               ;   
  ARCHIVE CAMUS =               ;   
