    const    err_OPL_neznamy_prev          = 3;
             err_OPL_neznamy_task          = 4;
             err_OPL_chyba_task            = 5;

             err_OPL_neuvedene_typy        = 6;
             err_OPL_neuvedeny_typ         = 10;
             err_OPL_neznamy_typ           = 11;

             err_OPL_typ_rych              = 14;
             err_OPL_typ_vyska             = 16;

             err_OPL_neznamy_ob            = 65;
             err_OPL_chybna_cinnost_ob     = 66;
             err_OPL_nezname_zs            = 69;

             err_OPL_vysky_rozsah          = 80;

             err_OPL_chyba_letisko         = 300;
             err_OPL_neopravnene_letisko   = 310;
             err_OPL_dvz_letisko           = 320;
