     const  tit_fplsrc_RPL      = 'R';
            tit_fplsrc_PLN      = 'P';
            tit_fplsrc_FPL      = 'F';
            tit_fplsrc_FDA      = 'A';
            {tit_fplsrc_EST     = 'E';}


            tit_FPL4_PLAN       = 'ATS-ROUTE FLIGHT PLAN';
            tit_FPL4_PREHLAD    = 'ATS-ROUTE FLIGHT PLANs';

            tit_FPL4prea        = 'Day flight plans has been preactivated';


            tit_FPL4notapproved = 'Flight plan was not approved. Activate ?';
            err_FPL4notapproved = 10;
