    const  err_FPLM_7a_chyba                 = 1;
           err_FPLM_7a_vojensky              = 2;
           err_FPLM_7a_iny                   = 3;

           err_FPLM_7a_mimolet               = 10;
           err_FPLM_7a_prelet                = 11;
           err_FPLM_7a_letlet                = 12;

           err_FPLM_7a_letTSA                = 30;
           err_FPLM_7a_chybaTSA              = 31;
           err_FPLM_7a_letTSA_nemoze_dalsi   = 32;

           err_FPLM_8a                       = 20;
           err_FPLM_8b                       = 22;

           err_FPLM_let_mimo_FIR             = 40;
           err_FPLM_let_cez_P                = 41;
           err_FPLM_let_cez_FUA_PLAN         = 45;
           err_FPLM_let_cez_FUA_ACT          = 46;

           err_FPLM_nezname_dep              = 50;
           err_FPLM_nezname_arr              = 51;
           err_FPLM_chyba_bod_MZP            = 55;
           err_FPLM_chyba_cas_MZP            = 56;
           err_FPLM_neznamy_kod              = 57;

           err_FPLM_let_PTSA                 = 80;


           err_FPLM_9b_neznamy_typ           = 110;
           err_FPLM_9b_vojensky_typ          = 111;
           err_FPLM_9b_nevojensky_typ        = 112;
