       const

            { -------------------------
               SLOVAK
              -------------------------
            }
             {$IFDEF SLOVAK}
               ask_kridlo                  = 'Pl n pre kr¡dlo ?';
               tit_zmeneny_FPLM            = 'Obsah alebo stav FPL bol medzi‡asom zmenen˜.';
               tit_nova_pripominenka_FPLM  = 'Bola vy‘iadan  nov  pripomienka k letu.';
             {$ENDIF}


            { -------------------------
               CZECH
              -------------------------
            }
             {$IFDEF CZECH}
               ask_kridlo                  = 'Pl n pro k©¡dlo ?';
               tit_zmeneny_FPLM            = 'Obsah anebo stav FPL byl medzi‡asem zmˆnen.';
               tit_nova_pripominenka_FPLM  = 'Byla vy‘ dan  nov  p©ipom¡nka k letu.';
             {$ENDIF}


            { -------------------------
               ENGLISH
              -------------------------
            }
             {$IFDEF ENGLISH}
               ask_kridlo                  = 'Uncompleted plan ?';
             {$ENDIF}
