    const {$IFDEF RPL}
           RUSSIAN_RPL  : bool = true;
          {$ENDIF}
           RUSSIAN_FPL  : bool = true;
           RUSSIAN_FPD  : bool = true;


    const  cfgRUSSIAN_FPL           = 'CYRILLIC FPL';
           cfgRUSSIAN_FPD           = 'CYRILLIC FPD';

           cfg_rngREQ               = 'REQ LIMIT';
           cfg_rngDEP               = 'DEP LIMIT';

           cfg_TARGET_REFRESH       = 'TARGET REFRESH';


