       const {$IFDEF SLOVAK}
               tit_AUP   = ' NOTAM AUP - PLèN VYUíITIA VZDUõNêHO PRIESTORU ';
               tit_UUP   = ' NOTAM UUP - DOPLNOK PLèNU VYUíITIA VZDUõNêHO PRIESTORU ';

               tit_rec_AUP = 'Bol prijatò pl†n AUP ';
               tit_rec_UUP = 'Bol prijatò pl†n UUP ';
             {$ENDIF}

             {$IFDEF CZECH}
               tit_AUP   = ' NOTAM AUP - PLèN VYUíITã VZDUõNêHO PROSTORU ';
               tit_UUP   = ' NOTAM UUP - DOPLNEK PLèNU VYUíITã VZDUõNêHO PROSTORU ';
             {$ENDIF}

             {$IFDEF ENGLISH}
             {$ENDIF}
