    const  err_FUA_let                      = 99;

           err_FUA_sprava_not_found         = 101;
           err_FUA_sprava_head_not_found    = 102;

           err_FUA_typ                      = 110;
           err_FUA_cis                      = 115;
           err_FUA_ref                      = 116;

           err_FUA_ods                      = 120;
           err_FUA_adr                      = 121;

           err_FUA_val                      = 130;
           err_FUA_zac                      = 131;
           err_FUA_kon                      = 132;
           err_FUA_dlz                      = 133;


