       const {$IFDEF SLOVAK}
               tit_syn_last = 'Prehåad poslednòch spr†v SYNOP';
               tit_syn_arch = 'Prehåad archivovanòch spr†v SYNOP';
             {$ENDIF}


             {$IFDEF CZECH}
               tit_syn_last = 'P©ehled posledn°ch zpr†v SYNOP';
               tit_syn_arch = 'P©ehled archivovanòch zpr†v SYNOP';
             {$ENDIF}


             {$IFDEF ENGLISH}
               tit_syn_last = ;
               tit_syn_arch = ;
             {$ENDIF}
