
      const  tit_PLN_PREHLAD  = 'PLN FLIGHT CLEARANCEs';

             ask_PLN_DEL      = 'PLN will be deleted. Are you sure ?';
             tit_PLN_PENDED   = 'Pended PLN message';
             tit_PLN_CHECK    = 'Checking an integrity of PLN message...';
             tit_PLN_ITEM     = 'Processing item of PLN message ';


             err_pln_other_adress = 1;
             err_pln_unknown_date = 2;
             err_pln_validity     = 3;
