      const  pln_PND : bool = true;
             pln_ADR : bool = true;
             pln_FPL : bool = false;
             pln_ERR : bool = true;

             pln_assign_15  : bool = false;  { snazi sa priradit trat z mnoziny standartnych,
                                               ak su uvedene len vstupny a vystupny bod
                                             }

      const  RUSSIAN_PLN : bool = true;


      {const  extPLN = 'PLN'; -> definovane v Archiv, kvoli jednoznacnosti pripon... }

      const  is_PLN : bool = false;
