       const {$IFDEF SLOVAK}
               tit_PRN_VLIS      = 'Nariadenie VLIS o vyu‘it¡ vzdu¨n‚ho priestoru';
               tit_PRN_          = 'NOTAM VLIS o vyu‘it¡ vzdu¨n‚ho priestoru';
               tit_PRN           = 'NOTAM-y VLIS o vyu‘it¡ vzdu¨n‚ho priestoru';

               tit_rec_PRN_VLIS  = 'Bolo prijat‚ nariadenie VLIS o vyu‘it¡ vzdu¨n‚ho priestoru ';
             {$ENDIF}

             {$IFDEF CZECH}
             {$ENDIF}

             {$IFDEF ENGLISH}
             {$ENDIF}
