       const {$IFDEF SLOVAK}

               mnu_PRS_PLAN      = {$IFDEF FUA}
                                     {$IFDEF AMC} ' PL~è~N VYUíITIA PRIESTORU (AMC)      F7 ';
                                     {$ELSE}      ' PL~è~N VYUíITIA PRIESTORU (AMC)      F7 ';
                                     {$ENDIF}
                                   {$ELSE}        ' PL~è~N VYUíITIA PRIESTORU   F7 ';
                                   {$ENDIF}


               mnu_PRS_CPY       = ' ~K~ïPIA PLèNU ';
               mnu_PRS_CHG       = ' O~P~RAVA PLèNU';
               mnu_PRS_CNL       = ' Z~R~UõENIE P~LèNU ';

               mnu_PRS_REQ       = ' SC~H~VèLENIE PLèNU ';
               mnu_PRS_ACC       = ' ODS~ó~HLASENIE PLèNU ';
               mnu_PRS_DEC       = ' ZAM~I~ETNUTIE PLèNU ';

               mnu_PRS_DEP       = ' ZA~Ä~ATIE ÄINNOSTI V PRIESTORE ';
               mnu_PRS_ACT       = ' Z~M~ENA VO VYUíVANã PRIESTORU ';
               mnu_PRS_BRK       = ' PR~E~RUõENIE ÄINNOSTI ';
               mnu_PRS_CNT       = ' PO~K~RAÄOVANIE V ÄINNOSTI ';
               mnu_PRS_ARR       = ' UK~O~NÄENIE ÄINNOSTI ';
             {$ENDIF}


             {$IFDEF CZECH}
               mnu_PRS_PLAN  = {$IFDEF FUA}
                                  {$IFDEF AMC} ' P~L~èN VYUíITã PROSTORU (AMC)       F7 ';
                                  {$ELSE}      ' P~L~èN VYUíITã PROSTORU (AMC)       F7 ';
                                  {$ENDIF}
                               {$ELSE}         ' P~L~èN VYUíITã PROSTORU   F7 ';
                               {$ENDIF}

               mnu_PRS_CPY       = ' ~K~OPIE PLèNU ';
               mnu_PRS_CNL       = ' ~Z~RUõENã P~LèNU ';
               mnu_PRS_CHG       = ' OPRAVA/~A~KTUALIZACE ';

               mnu_PRS_REQ       = ' SPRACOVèNã ~í~èDOSTI ';
               mnu_PRS_ACC       = ' SCH~V~èLENã PLèNU ';
               mnu_PRS_DEC       = ' ZAM~ã~TNUTã PLèNU ';

               mnu_PRS_DEP       = ' ZA~Ä~èTEK ÄINNOSTI V PROSTORU ';
               mnu_PRS_ACT       = ' Z~M~ENA VO VYUíãVANã PROSTORU ';
               mnu_PRS_BRK       = ' Pû~E~RUõENã ÄINNOSTI ';
               mnu_PRS_CNT       = ' PO~K~RAÄOVèNã V ÄINNOSTI ';
               mnu_PRS_ARR       = ' UK~O~NÄENã ÄINNOSTI ';
             {$ENDIF}


             {$IFDEF ENGLISH}
               mnu_PRS_PLAN  = {$IFDEF FUA}
                                 {$IFDEF AMC}
                                    ' P~L~èN VYUíITIA PRIESTORU (AMC)      F7 ';
                                 {$ELSE}
                                    ' P~L~èN VYUíITIA PRIESTORU (AMC)      F7 ';
                                 {$ENDIF}
                               {$ELSE}
                               ' USE OF AREA P~L~AN     F7 ';
                               {$ENDIF}

               mnu_PRS_CPY   = ' COP~Y~ OF PLAN ';
               mnu_PRS_CNL   = ' CA~N~CEL OF PLAN ';
               mnu_PRS_CHG   = ' ~C~HANGE OF PLAN ';
               mnu_PRS_DEP   = ' ~S~TART USE OF AREA ';
               mnu_PRS_ACT   = ' ~U~PDATE USE OF AREA ';
               mnu_PRS_BRK   = ' ~B~REAK USE OF AREA ';
               mnu_PRS_CNT   = ' C~O~NTINUE IN USE OF AREA ';
               mnu_PRS_ARR   = ' ~T~ERMINATE USE OF AREA ';
             {$ENDIF}
