       const {$IFDEF SLOVAK}
               tit_PRZ_          = '’IADOS†';

               tit_przPLAN       = '’iadosŸ o pridelenie priestoru';
               tit_przCHG        = 'Oprava ‘iadosti o pridelenie priestoru';
               ask_przCNL        = 'Zru¨iŸ ‘iadosŸ o pridelenie priestoru';
               tit_przCNL        = 'Zru¨enie ‘iadosti o pridelenie priestoru';
               tit_przPLANNED    = '’iadosti o pridelenie priestorov';

               PRZPLAN           = ' ’~I~ADOS† O PRIDELENIE PRIESTORU (VLIS) ';
               PRZCPY            = ' ~K~•PIA ’IADOSTI ';
               PRZCHG            = ' OPRAVA ’IA~D~OSTI ';
               PRZCNL            = ' ZRU~›~ENIE ’IADOSTI ';
             {$ENDIF}


             {$IFDEF CZECH}
               ?tit_przPLAN       = '’iadosŸ o pridelenie priestoru';
               tit_przCHG        = 'Oprava ‘iadosti o pridelenie priestoru';
               tit_przCNL        = 'Zru¨enie ‘iadosti o pridelenie priestoru';
             {$ENDIF}


             {$IFDEF ENGLISH}
               ?tit_przPLAN       = '’iadosŸ o pridelenie priestoru';
               tit_przCHG        = 'Oprava ‘iadosti o pridelenie priestoru';
               tit_przCNL        = 'Zru¨enie ‘iadosti o pridelenie priestoru';
               tit_przPLANNED    = '’iadosti o pridelenie priestorov';
             {$ENDIF}
