       const  {$IFDEF SLOVAK}
                rep_schopnost     = 'Hl†senie o stave/schopnosti';
                tit_schopnost     = 'Schopnosü';
                tit_na            = 'na';
                tit_stav_         = 'Stav';
                tit__prostriedkov = 'prostriedkov';
                tit_TQGO          = 'TQGO';
                tit_MQGO          = 'MQGO';

                ask_QGOCNL        = 'Zru®iü hl†senie o schopnosti';

                tit_QGO           = 'Hl†senia o stave/schopnosti';
                tit_QGO_CHG       = 'Aktualiz†cia hl†senia o stave/schopnosti';
                msg_QGO_RPL_CHG   = 'OPRAVA VZORU HLèSENIA O SCHOPNOSTI ';
                ask_QGO_RPL_CNL   = 'Zru®iü vzor hl†senia o schopnosti pre';
              {$ENDIF}

              {$IFDEF CZECH}
                rep_schopnost     = 'Hl†®en° o stavu/schopnosti';
                tit_schopnost     = 'Schopnost';
                tit_na            = 'na';
                tit_stav_         = 'Stav';
                tit__prostriedkov = 'prost©edkñ';
                tit_TQGO          = 'TQGO';
                tit_MQGO          = 'MQGO';

                ask_QGOCNL        = 'Zru®it hl†®en° o schopnostech';

                tit_QGO           = 'Hl†senia o stave/schopnosti';
                tit_QGO_CHG       = 'Aktualiz†cia hl†senia o stave/schopnosti';
                msg_QGO_RPL_CHG   = 'OPRAVA VZORU HLèõENã O SCHOPNOSTI ';
                ask_QGO_RPL_CNL   = 'Zru®it vzor hl†®en° o schopnosti pro';
              {$ENDIF}

              {$IFDEF ENGLISH}
                rep_schopnost     = 'Hl†senie o stave/schopnosti';
                tit_schopnost     = 'Schopnosü';
                tit_na            = 'na';
                tit_stav_         = 'Stav';
                tit__prostriedkov = 'prostriedkov';
                tit_TQGO          = 'TQGO';
                tit_MQGO          = 'MQGO';

                ask_QGOCNL        = 'Zru®iü hl†senie o schopnosti';

                tit_QGO           = 'Hl†senia o stave/schopnosti';
                tit_QGO_CHG       = 'Aktualiz†cia hl†senia o stave/schopnosti';
                msg_QGO_RPL_CHG   = 'OPRAVA VZORU HLèSENIA O SCHOPNOSTI ';
                ask_QGO_RPL_CNL   = 'Zru®iü vzor hl†senia o schopnosti pre';
              {$ENDIF}

