      const  tit_RPL_PLAN     = 'REPETIVE FLIGHT PLAN';
             tit_RPL_PREHLAD  = 'REPETIVE FLIGHT PLANs';

             tit_RPL_SOURCE   = 'RPL text file source directory';

             tit_rpl_copy      = 'COPY OF RPL';
             tit_rpl_chg       = 'CHANGE OF RPL';
             tit_rpl_cnl       = 'CANCELATION OF RPL';
             tit_rpl_brk       = 'RPL DEACTIVATION';
             tit_rpl_cnt       = 'RPL REACTIVATION';
             tit_rpl_fpl       = 'FLIGHT PLAN INITIALIZATION';


             tit_ext_to_rpl    = 'Processing RPL data file';
             tit_rpl_to_fpl    = 'Processing RPL to FPL';

             tit_rpl_deactived = 'RPL was deactived.';
             tit_rpl_reactived = 'RPL was reactived.';

             tit_ext_err       = 'Error list of last processed external RPL file';


             tit_rpl_replace   = 1; {'RPL database is to be updated and replaced by new one.';}
             tit_rpl_extend    = 2; {'RPL database is to be extended by new items.';}

             ask_rpl_backup    = 10;
             ask_rpl_restore   = 11;
             tit_rpl_no_backup = 12; {'There is no backuped RPL database. Cannot restore it.');}
             tit_rpl_restored  = 13; {'RPL database has been restored'}

             ask_rpl_make      = 20;


             mnu_RPL_CHG_      = ' ~C~ORRECT ';
             mnu_RPL_BRK_      = ' ~D~EACTIVATE  ';
             mnu_RPL_CNT_      = ' ~R~EACTIVATE  ';
