      const

            {$IFDEF SLOVAK}
              tit_MSG           = 'Spr va';
              tit_TLG           = 'Telegram';

              tit_MSGL          = 'V˜pis spr v';
              tit_MSGS          = 'V˜pis odoslan˜ch spr v';
              tit_MSGR          = 'V˜pis doru‡en˜ch spr v';

              tit_sendMSG       = 'Odoslanie spr vy';
              tit_sendMSGADR    = 'Adres t spr vy';

             { dorucenie
             }
              tit_MSG_ack       = 'Spr va bola doru‡en .';
              tit_MSG_not_ack   = 'Spr va nebola doru‡en .';
              tit_MSG_sent      = 'Spr va bola odoslan .';

             { spracovanie
             }
              tit_MSG_not_rec_  = 'nebola doru‡en ';
              tit_MSG_acc_      = 'bola prevzat  o';
              tit_MSG_not_acc_  = 'nebola prevzat ';
              tit_MSG_not_read_ = 'nebola spracovan ';

             { zobrazenie
             }
              tit_MSG_not_rec   = 'nedoru‡en ';
              tit_MSG_acc       = 'prevzat ';
              tit_MSG_not_acc   = 'neprevzat ';
              tit_MSG_not_read  = 'nespracovan ';
              tit_MSG_in_lam    = 'potvrdenie v LAM';

              tit_MSGod         = 'Od ';
              tit_MSGpre        = 'Pre ';
              tit_MSGpod        = 'podan ';
              tit_MSGzob        = 'zobrazen ';

             { ine
             }
              tit_SPRadr_all    = ';  v¨etky uzly prij¡maj£ce spr vy';
              tit_SPRadr_opl    = ';  v¨etky pracovisk  OPL';
              tit_SPRadr_let    = ';  v¨etky letisk ';

              tit_MSGreport     = 'Hl senie od ';
              tit_SPRlam        = 'Prevzatie spr vy';
            {$ENDIF}


            {$IFDEF CZECH}
              tit_MSG           = 'Zpr va';
              tit_TLG           = 'Telegram';

              tit_MSGL          = 'V˜pis zpr v';
              tit_MSGS          = 'V˜pis odeslan˜ch zpr v';
              tit_MSGR          = 'V˜pis doru‡en˜ch zpr v';

              tit_sendMSG       = 'Odesl n¡ zpr vy';
              tit_sendMSGADR    = 'Adres t zpr vy';

             { dorucenie
             }
              tit_MSG_ack       = 'Zpr va byla doru‡ena.';
              tit_MSG_not_ack   = 'Zpr va nepro¨la.';
              tit_MSG_sent      = 'Zpr va byla odeslan .';

             { spracovanie
             }
              tit_MSG_not_rec_  = 'nebyla doru‡ena';
              tit_MSG_acc_      = 'byla p©evzata o';
              tit_MSG_not_acc_  = 'nebyla p©evzata';
              tit_MSG_not_read_ = 'nebyla zpracov na';

             { zobrazenie
             }
              tit_MSG_not_rec   = 'nedoru‡ena';
              tit_MSG_acc       = 'p©evzata';
              tit_MSG_not_acc   = 'nep©evzata';
              tit_MSG_not_read  = 'nezpracov na';
              tit_MSG_in_lam    = 'potvrzen¡ v LAM';

              tit_MSGod         = 'Od ';
              tit_MSGpre        = 'Pro ';
              tit_MSGpod        = 'podan ';
              tit_MSGzob        = 'zobrazen ';

             { ine
             }
              tit_SPRadr_all    = ';  v¨echny uzly p©ij¡maj¡ci zpr vy';
              tit_SPRadr_opl    = ';  v¨echny pracovi¨tˆ vojenk‚ho žLP';
              tit_SPRadr_let    = ';  v¨echny leti¨tˆ';

              tit_MSGreport     = 'Hl ¨en¡ od ';
              tit_SPRlam        = 'P©evzet¡ zpr vy';
            {$ENDIF}


            {$IFDEF ENGLISH}
              tit_MSG           = 'Message';
              tit_TLG           = 'Telegramm';

              tit_MSGL          = 'Messages list';
              tit_MSGS          = 'List of sended mesages';
              tit_MSGR          = 'List of received mesages';

             { dorucenie
             }
              tit_MSG_ack       = 'Message was received.';
              tit_MSG_not_ack   = 'Message was not received.';
              tit_MSG_sent      = 'Message has been sent.';

             { spracovanie
             }
              tit_MSG_not_rec_  = 'was not delivered';
              tit_MSG_acc_      = 'has been accepted'
              tit_MSG_not_acc_  = 'was not accepted';
              tit_MSG_not_read_ = 'was not processed';

             { zobrazenie
             }
              tit_MSG_not_rec   = 'undelivered';
              tit_MSG_acc       = 'accepted';
              tit_MSG_not_acc   = 'unaccepted';
              tit_MSG_not_read  = 'unprocessed';
              tit_MSG_in_lam    = 'LAM';

              tit_MSGod         = 'From ';
              tit_MSGpre        = 'For ';
              tit_MSGpod        = 'sent';
              tit_MSGzob        = 'displayed';

             { ine
             }

              tit_SPRadr_all    = ';  all nodes receiving messages';
              tit_SPRadr_opl    = ';  ';
              tit_SPRadr_let    = ';  ';

              tit_SPRlam        = 'Logical acknowlegment of message';
            {$ENDIF}
