   {$IFDEF SLOVAK}
     const  mnu_pis_STRIP_MINI = 'UPREDNOSTNENIE MINI-FORMèTU STRIPU';
            mnu_pis_STRIP_COR  = 'INDIKèCIA OPRAVY STRIPU';
            mnu_pis_STRIP_ACK  = 'ZOBRAZENIE DORUÄENIA STRIPU';

            mnu_miniSTRIP = ' FORMèT STRIPU ';
            mnu_MINI      = ' ~1.~ MINI STRIPY   ';
            mnu_SHORT     = ' ~2.~ KRèTKE STRIPY ';
            mnu_LARGE     = ' ~3.~ óPLNê STRIPY  ';
   {$ENDIF}


   {$IFDEF CZECH}
     const  mnu_pis_STRIP_MINI = 'UPûEDNOSTNâNã MINI-FORMèTU STRIPU';
            mnu_pis_STRIP_COR  = 'INDIKACE OPRAVY STRIPU';
            mnu_pis_STRIP_ACK  = 'ZOBRAZENã DORUÄENã STRIPU';

            mnu_miniSTRIP = ' FORMèT STRIPU ';
            mnu_MINI      = ' ~1.~ MINI STRIPY   ';
            mnu_SHORT     = ' ~2.~ KRèTKE STRIPY ';
            mnu_LARGE     = ' ~3.~ óPLNê STRIPY  ';
   {$ENDIF}


   {$IFDEF ENGLISH}
     const  mnu_pis_STRIP_MINI = 'MINI-FORMAT STRIP PREFERENCE';
            mnu_pis_STRIP_COR  = 'STRIP CORRECTION INDICATION';
            mnu_pis_STRIP_ACK  = 'STRIP DELIVERY INDICATION';

            mnu_miniSTRIP = ' STRIP''S FORMAT ';
            mnu_MINI      = ' ~1.~ MINI STRIPs  ';
            mnu_SHORT     = ' ~2.~ SHORT STRIPs ';
            mnu_LARGE     = ' ~3.~ LONG STRIPs  ';
   {$ENDIF}
