
            {$IFDEF SLOVAK}
       const tit_TLGadr  = 'Adres t(i) spr vy';
             tit_TLGtlg  = 'Priorita spr vy';
             tit_TLGtxt  = 'Text spr vy';

             tit_MSG     = 'SPRVA';
             tit_TLG     = 'TELEGRAM';
             msg_NO_ADR  = 'Nie s£ uvedn¡ adres ti spr vy.';
            {$ENDIF}


            {$IFDEF CZECH}
       const tit_TLGadr  = 'Adres t(i) spr vy';
             tit_TLGtlg  = 'Priorita spr vy';
             tit_TLGtxt  = 'Text spr vy';

             tit_MSG     = 'SPRVA';
             tit_TLG     = 'TELEGRAM';
             msg_NO_ADR  = 'Nie s£ uvedn¡ adres ti spr vy.';
            {$ENDIF}


            {$IFDEF ENGLISH}
       const tit_TLGadr  = 'MESSAGE ADRESSES'        {$IFDEF RUSSIAN}+' / €€‚…ˆ… ’…‹…ƒ€ŒŒ›' {$ENDIF};
             tit_TLGtlg  = 'MESSAGE PRIORITY'        {$IFDEF RUSSIAN}+' / Š€’…ƒŽˆŸ ‘Ž—Ž‘’ˆ'   {$ENDIF};
             tit_TLGtxt  = 'MESSAGE TEXT'            {$IFDEF RUSSIAN}+' / ’…Š‘’ ’…‹…ƒ€ŒŒ›'      {$ENDIF};

             tit_TLGreg  = 'REGISTRATION'            {$IFDEF RUSSIAN}+' / …ƒˆ‘’€–ˆŸ'           {$ENDIF};
             tit_TLGdat  = 'DATE'                    {$IFDEF RUSSIAN}+' / —ˆ‘‹Ž'                 {$ENDIF};
             tit_TLGutc  = 'UTC TIME'                {$IFDEF RUSSIAN}+' / UTC ‚…ŒŸ'             {$ENDIF};

             tit_MSG     = 'MESSAGE';
             tit_TLG     = 'TELEGRAMM'               {$IFDEF RUSSIAN}+' / ’…‹…ƒ€ŒŒ€'            {$ENDIF};
             msg_NO_ADR  = 'There is no adrress in the telegram.';

             tit_RTS     = 'Žƒ€ˆ—…ˆ… €Ž’›';
             tit_RTO     = 'Ž’Œ…€ Žƒ€ˆ—…ˆŸ €Ž’›';

             tit_RVM     = 'Žƒ€ˆ—…ˆ… …†ˆŒ€ Ž‹…’Ž‚';
             tit_RVI     = 'Ž’Œ…€ Žƒ€ˆ—…ˆˆ Ž‹…’Ž‚';

             tit_AREA    = '€‰Ž “‚„/“—€‘’ŽŠ ‚Ž‡„“˜Ž‰ ’€‘‘›';
             tit_UTCb    = '‚…ŒŸ €—€‹€';
             tit_UTCe    = '‚…ŒŸ Ž’Œ…›';
             tit_DATb    = '—ˆ‘‹Ž €—€‹€';
             tit_DATe    = '—ˆ‘‹Ž Ž’Œ…›';

             tit_TLG_PREHLAD  = 'TELEGRAMMs';
            {$ENDIF}

