       const  {$IFDEF SLOVAK}

                tit_zam           = 'PLèN ZAMESTNANIA LETISKA';
                tit_zam_          = ' zamestnania ';
                tit_na_           = ' na ';

                tit_formZAM       = 'Pl†n zamestnania letiska';
                tit_planZAM       = 'Pl†novanÇ zamestnania';
                tit_actZAM        = 'Akt°vne zamestnania';
                tit_info_ZAM      = 'Pl†n zamestnania pre';

                tit_zamCHG        = 'OPRAVA PLèNU ZAMESTNANIA';
                tit_zamCNL        = 'ZRUõENIE PLèNU ZAMESTNANIA';
                ask_zamCNL        = 'Zru®iü pl†n zamestnania';
                tit_zamDEP        = 'ZAÄIATOK ZAMESTNANIA LETISKA';
                tit_zamBRK        = 'PRERUõENIE ZAMESTNANIA';
                tit_zamCNT        = 'POKRAÄOVANIE ZAMESTNANIA';
                tit_zamARR        = 'UKONÄENIE ZAMESTNANIA';
                tit_zamARRtime    = 'Äas ukonáenia zamestnania ';
                tit_zamLETOV      = 'AKTUALIZèCIA POÄTU LETOV';
                tit_zamLETOVdna   = 'D†tum zamestnania';

                tit_LETOV_        = ' POÄET LETO~V~ ';

                msg_ZAM_RPL_CHG   = 'OPRAVA VZORU PLèNU ZAMESTNANIA';
                ask_ZAM_RPL_CNL   = 'Zru®iü vzor pl†nu zamestnania pre';

                tit_ZAMprea       = 'Preaktivuj£ sa pl†ny zamestnan°.';

                tit_zamPLAN_L     = 'Pl†novanÇ zamestnania';
                tit_zamACT_L      = 'AktivovanÇ zamestnania';
                tit_zamARR_L      = 'UkonáenÇ zamestnania';
                tit_zamARR_A      = 'V®etky pl†ny zamestnan°';

                err_TMA_NOT_FOUND = 'Mapa priestoru letiska nebola n†jden†, zobraz° sa ako kruh s polomerom ';
              {$ENDIF}

              {$IFDEF CZECH}

                tit_zam_          = ' zamàstn†n° ';

                tit_formZAM       = 'Pl†n zamàstn†n° leti®tà';
                tit_planZAM       = 'Pl†novanÇ zamàstn†n°';
                tit_actZAM        = 'Aktivn° zamàstn†n°';
                tit_info_ZAM      = 'Pl†n zamàstn†n° pro';

                tit_zamCHG        = 'Oprava pl†nu zamàstn†n°';
                tit_zamCNL        = 'Zruõen° pl†nu zamàstn†n°';
                ask_ZAMCNL        = 'Zru®it plan zamàstn†n°';
                tit_zamDEP        = 'Zaá†tek zamàstn†n° leti®tà';
                tit_zamBRK        = 'P©eru®en° zamàstn†n°';
                tit_zamCNT        = 'Pokraáov†n° zamàstn†n°';
                tit_zamARR        = 'Ukonáen° zamàstn†n°';
                tit_zamARRtime    = 'Äas ukonáen° zamàstn†n° ';


                msg_ZAM_RPL_CHG   = 'OPRAVA VZORU PLèNU ZAMâSTNèNã';
                ask_ZAM_RPL_CNL   = 'Zru®it vzor pl†nu zamàstn†n° pro';

                tit_ZAMprea       = 'P©eaktivuj° se pl†ny zamàstn†n°.';

                err_TMA_NOT_FOUND = 'Mapa prostoru leti®tà nebyla nalezena, zobraz° se jako kruh s polomàrem ';
              {$ENDIF}

              {$IFDEF ENGLISH}

                tit_zam_          = ' activities ';

                tit_formZAM       = 'Airport activities plan';
                tit_planZAM       = 'Planned airport activities';
                tit_actZAM        = 'Airport activities';

                tit_info_ZAM      = 'Airport activity on';

              {$ENDIF}

