          {
          ‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
          €                               €
          €  Doc4444                      €
          €‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€
          }

            cmERR_DEL             = 42000;
            cmERR_SAVE            = 42001;

            cmICAO_INI            = 42010;
            cmICAO_STREAM_ARCHIVE = 42011;


            cmICAO_ALR            = 42020;
            cmICAO_ERS            = 42021;
            cmICAO_FLI            = 42022;

            cmTLG_EDIT            = 42031;
            cmTLG_DEL             = 42032;
            cmTLG_PEND            = 42033;  { zakaze spracovnanie tlg prislusnej kategorie }


          {
          ‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
          €                               €
          €  AFTN                         €
          €‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€
          }

            cmAFTN_INFO           = 43020;
            cmAFTN_ERLINE         = 43021;
            cmAFTN_2LINE          = 43022;

            cmPREHLAD_AFTN        = 43040;
            cmPREHLAD_AFTN_A      = 43041;
            cmARCHIV_AFTN         = 43090;


          {
          ‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
          €                               €
          €  OLDI                         €
          €‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€
          }

            cmOLDI_INFO           = 48100;

            cmOLDI_TEST_FPL       = 48111;
            cmOLDI_TEST_CHG       = 48112;
            cmOLDI_TEST_DLA       = 48113;
            cmOLDI_TEST_CNL       = 48125;
            cmOLDI_TEST_ACT       = 48115;
            cmOLDI_TEST_REV       = 48116;
            cmOLDI_TEST_ERR       = 48117;

            cmOLDI_TEST_TrTimeout = 48120;
            cmOLDI_disable_SVC    = 48121;


          {
          ‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
          €                               €
          €  INE                          €
          €‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€
          }

            spr_ASOC              = 48400;


            cmOPL_ERLINE          = 48521;
            cmZIADOST_AUP         = 48550;
            cmZIADOST_RTZ         = 48551;
            cmARCHIV_OPL          = 48591;
            cmARCHIV_OPS          = 48592;

            cmARCHIV_VERA         = 48598;


            cmASOC_TEST_FPL       = 48801;
            cmASOC_TEST_CHG       = 48802;
            cmASOC_TEST_DLA       = 48803;
            cmASOC_TEST_CNL       = 48804;

            cmASOC_TEST_ACT       = 48805;
            cmASOC_TEST_REV       = 48806;

            cmASOC_TEST_DEP       = 48807;
            cmASOC_TEST_ARR       = 48808;
            cmASOC_TEST_CPL       = 48809;

            cmASOC_INIT_FPLC      = 48810;
            cmASOC_INIT_FPLM      = 48811;
            cmASOC_INIT_FPLO      = 48812;

            cmARCHIV_ASOC         = 48890;


            cmBGU_ERROR           = 48900;


          {
          ‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
          €                               €
          €  SERVER                       €
          €‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€
          }

            cmARCHIV_COM          = 49000;
            cmARCHIV_NET          = 49001;
            cmARCHIV_DAR          = 49005;

            cmARCHIV_ASTA         = 49010;
            cmARCHIV_CAMUS        = 49011;
