          {
          ‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
          €                       €
          € L4444/FPL,TLG         €
          €‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€
          }

           { RPL
           }
            cm_RPL                = 11300;
            cm_RPLchg             = 11301;
            cm_RPLbrk             = 11302;
            cm_RPLcnt             = 11303;
            cm_RPLcnl             = 11304;

            cm_RPLchyby           = 11310;
            cm_RPLdokonci         = 11315;
            cm_RPLadd             = 11316;
            cm_RPLreplace         = 11317;
            cm_RPLcorrect         = 11318;
            cm_RPLrestore         = 11319;

            cm_RPLspracuj         = 11320;

            cm_RPLmake            = 11340;
            cm_RPLpended          = 11341;

            cm_RPLview            = 11350;
            cm_RPLdraw            = 11351;
            cm_RPLprint           = 11353;
            cm_RPLsend            = 11354;

            cmPREHLAD_RPL         = 11370;



           { FPL4
           }
            cm_FPL                = 11401;
            cm_CHG                = 11402;
            cm_DLA                = 11403;
            cm_CNL                = 11404;

            cm_ABI                = 11410;
            cm_ACT                = 11411;
            cm_ACT_FPD            = 11412;

            cm_DEP                = 11421;
            cm_ARR                = 11422;

            cm_FLA                = 11423;
            cm_FLI                = 11424;

            cm_CPL                = 11425;
            cm_EST                = 11426;
            cm_ETO                = 11427;

            cm_MZA                = 11428;
            cm_MZD                = 11429;


            cmFPL4view            = 11450;
            cmFPL4view_strip      = 11451;
            cmFPL4draw            = 11452;
            cmFPL4print           = 11453;
            cmFPL4send            = 11454;


            cmPREHLAD_FPL4               = 11470;
            cmPREHLAD_FPL4_PPL           = 11471;
            cmPREHLAD_FPL4_ARCH          = 11472;

            cmPREHLAD_FPL4D_ARCH         = 11480;
            cmPREHLAD_FPL4D_PPL          = 11481;
            cmPREHLAD_FPL4D_INACTIVATED  = 11482;
            cmPREHLAD_FPL4D_PREACTIVATED = 11483;
            cmPREHLAD_FPL4D_PROPOSED     = 11484;
            cmPREHLAD_FPL4D_COORDINATED  = 11485;
            cmPREHLAD_FPL4D_NOTACTIVED   = 11487;
            cmPREHLAD_FPL4D_REALISED     = 11488;
            cmPREHLAD_FPL4D_ALL          = 11489;



           { PLN
           }
            cm_PLNpended          = 11440;

            cmPREHLAD_PLN         = 11490;
            cmPREHLAD_PLN_PPL     = 11491;
            cmPREHLAD_PLN_ARCH    = 11492;



           { TLG
           }
            cm_ALR                = 11431;
            cm_RCF                = 11432;

            cm_PPL                = 11450;
            cm_PCH                = 11451;
            cm_SRQ                = 11453;
            cm_SLT                = 11455;
            cm_PLN                = 11456;


            cm_ANP                = 11510;
            cm_RTS                = 11511;
            cm_RTO                = 11512;
            cm_RVM                = 11513;
            cm_RVI                = 11514;


            cm_TLG                = 11600;

            cm_TLG_SSpended       = 11631;
            cm_TLG_FFpended       = 11632;
            cm_TLG_KKpended       = 11633;

            cmPREHLAD_TLG         = 11661;
            cmPREHLAD_TLG_ARCH    = 11662;

