      const cmPLAN_VIEW            = 6000;
            cmPLAN_DRAW            = 6001;
            cmPLAN_PRINT           = 6002;
            cmPLAN_SEND            = 6003;
            cmPLAN_HIDE            = 6004;
            cmPLAN_SHOW            = 6005;

            cm_PLAN_CHG            = 6021;
            cm_PLAN_CNL            = 6022;
            cm_PLAN_LAM            = 6022;
            cm_PLAN_ABI            = 6023;

            cm_PLAN_CHGACK         = 6024;
            cm_PLAN_ACC            = 6025;
            cm_PLAN_UNACC          = 6026;
            cm_PLAN_TRACK          = 6027;

            cm_DATA_VIEW           = 6030;
            cm_PLAN_VIEW           = 6031;
            cm_ROUTE_VIEW          = 6032;
            cm_PLAN_TYPE           = 6034;

            cm_PLAN_DRAW           = 6033;
            cm_PLAN_SEND           = 6034;
            cm_PLAN_PRINT          = 6035;
            cm_PLAN_COPY           = 6036;

            cm_PLAN_ZMAZ           = 6040;



            cmREQ_DLA              = 6101;      { odloz                        }
            cmREQ_ACK              = 6102;      { povol                        }
            cmREQ_CHG              = 6103;      { polena s opravou             }
            cmREQ_DCL              = 6104;      { zakaz                        }


          { vypocet ESTu
          }
            cmEST_DEP              = 6200;
            cmEST_EST              = 6201;
            cmEST_LAST             = 6202;
            cmEST_NEXT             = 6203;
            cmEST_SEL              = 6204;
            cmEST_NOPL             = 6205;



            cm_STATISTIKA_TEST               = 6500;
            cm_PRIEBEZNA_DENNA_STATISTIKA    = 6510;
            cm_PRIEBEZNA_MESACNA_STATISTIKA  = 6511;

            cm_UZATVORENA_DENNA_STATISTIKA   = 6550;
            cm_UZATVORENA_MESACNA_STATISTIKA = 6551;


            cm_DENNA_STATISTIKA_PRELETOV     = 6690;
            cm_ARCHIV_STATISTIKY_PRELETOV    = 6691;


            cm_FPS_EXPORT                    = 6910;