    {$IFDEF SLOVAK}
      const  tit_READ_CNL = 'D ta nie s£ n jden‚. PrehŒadaŸ zru¨en‚, neschv len‚ a ukon‡en‚ pl ny ?';
    {$ENDIF}

    {$IFDEF CZECH}
      const  tit_READ_CNL = 'Data nebyli nalezeny. P©ehledat zru¨en‚, neschv len‚ a ukon‡en‚ pl ny ?';
    {$ENDIF}

    {$IFDEF ENGLISH}
      const  tit_READ_CNL = 'Data has been not found. Search in canceled, not aproved or realized plans ?';
    {$ENDIF}
