
     const {$IFDEF SLOVAK}

             mnu_AIP       = 'A~I~P';
             tit_AIP       = 'AIP ';
             tit_AIP_      = 'AIP/ÄãSELNãK';

             tit_slnko_den = 'VùCHOD/ZèPAD D•A ';
             tit_slnko_rok = 'SLNKO POÄAS ROKA ';
             tit_slnko_dna     = 'Slnko d§a';
             tit_slnko         = 'Slnko ';
             tit_vychod_zapad  = 'Vòchod/z†pad';
             tit_vychod        = 'vòchod o';
             tit_zapad         = 'z†pad o';

             tit_typy_icao = 'TYPY LIETADIEL PODúA ICAO ';
             tit_typy_zzzz = '- NIEKTORê PßVODNê ICAO KïDY ';
             tit_typy_tsga = '- KïDY TYPOV PODúA TSGA ';
             tit_typy_mil  = '- VOJENSKê KïDY TYPOV ';
             tit_typ_data  = 'óDAJE O TYPE';

             tit_uz        = 'CIVILNã UíãVATELIA ';
             tit_uz_mil    = 'VOJENSKã UíãVATELIA ';
             tit_ulohy_mil = 'VOJENSKê óLOHY ';

             tit_ob        = 'VOJENSKê NAVIGAÄNê BODY ';
             tit_ndb       = 'NAVIGAÄNê BODY TRATã LPS ';

             tit_rte_ats   = 'TRATE LPS ';
             tit_rte_atss  = 'õTANDARTNê TRATE LPS ';
             tit_rte_mil   = 'VOJENSKê TRATE ';

             tit_abc       = 'VOJENSKê KïDY ORIENTAÄNùCH BODOV (ABECEDA) ';
             tit_abc_      = 'NèZVY ORIENTAÄNùCH BODOV PODúA ABECEDY ';

             tit_tsa       = 'PRIESTORY TSA ';
             tit_r         = 'PRIESTORY R ';

             tit_fl        = 'LETOVê HLADINY ';

             tit_aip_in    = 'DOMèCE LETISKè ';
             tit_aip_out   = 'ZAHRANIÄNê LETISKè ';
           {$ENDIF}


           {$IFDEF CZECH}
             mnu_AIP       = 'A~I~P';
             tit_AIP       = 'AIP ';
             tit_AIP_      = 'AIP/ÄãSELNãK';

             tit_slnko_den = 'VùCHOD/ZèPAD DNE  ';
             tit_slnko_rok = 'SLUNCE POÄAS ROKU ';
             tit_slnko_dna     = 'Slunce dne';
             tit_slnko         = 'Slunce';
             tit_vychod_zapad  = 'Vòchod/z†pad';
             tit_vychod        = 'vòchod o';
             tit_zapad         = 'z†pad o';


             tit_typy_icao = 'TYPY LETADEL ICAO ';
             tit_typy_zzzz = '- NâKTERê P¶VODNã ICAO KïDY ';
             tit_typy_tsga = '- KïDY TYP¶ PODLE TSGA ';
             tit_typy_mil  = '- VOJENSKê KïDY TYP¶ ';
             tit_typ_data  = 'óDAJE O TYPE';

             tit_uz        = 'CIVILNã UíãVATELê ';
             tit_uz_mil    = 'VOJENõTã UíãVATELê  ';
             tit_ulohy_mil = 'VOJENSKê óKOLY ';

             tit_rte_ats   = 'TRATâ LPS ';
             tit_rte_mil   = 'VOJENSKê TRATâ ';
             tit_rte_atss  = 'STANDARTNã TRATâ LPS ';

             tit_ob        = 'VOJENSKê OTOÄNê BODY ';
             tit_ndb       = 'NAVIGAÄNã BODY TRATã LPS ';

             tit_abc       = 'VOJENSKê KïDY ORIENTAÄNãCH BOD¶ ';
             tit_abc_      = 'NèZVY VOJENSKíCH ORIENTAÄNùCH BOD¶ ';

             tit_tsa       = 'PROSTORY TSA ';
             tit_r         = 'PROSTORY R ';

             tit_fl        = 'LETOVê HLADINY ';

             tit_aip_in    = 'DOMèCã LETIõTâ ';
             tit_aip_out   = 'ZAHRANIÄNã LETIõTâ ';
           {$ENDIF}


           {$IFDEF ENGLISH}
             mnu_AIP       = 'A~I~P';
             tit_AIP       = 'AIP ';
             tit_AIP_      = 'AIP, REGISTERS';

             tit_slnko_den = 'DAY SUNRISE/SUNSET ';
             tit_slnko_rok = 'SUNRISE/SUNSET ';
             tit_slnko_dna     = 'SUN ON DAY';
             tit_slnko         = 'SUN';
             tit_vychod        = 'sunrise in';
             tit_zapad         = 'sunset in';

             tit_typy_icao = 'AIRCRAFT TYPES CODES BY ICAO REGISTER ';
             tit_typy_zzzz = '- SOME OLDER CODES BY ICAO REGISTER ';
             tit_typy_tsga = '- AIRCRAFT TYPES CODES BY TSGA REGISTER ';
             tit_typy_mil  = '- AIRCRAFT CODES BY MILITARY REGISTER';
             tit_typ_data  = 'DATA OF TYPE';

             tit_uz        = 'CIVILIAN OPERATORS ';
             tit_uz_mil    = 'MILITARY OPERATORS ';
             tit_ulohy_mil = 'MILIRATY TASKS ';

             tit_rte_ats   = 'AIR TRAFFIC SERVICES ROUTES ';
             tit_rte_atss  = 'STANDART AIR TRAFFIC SERVICES ROUTES ';
             tit_ndb       = 'NAVIGATION POINTS OF ATS ROUTES ';

             tit_rte_mil   = 'MILITARY ROUTES ';
             tit_ob        = 'MILITARY NAVIGATION POINTS ';

             tit_abc       = 'MILITARY ORIENTATION CODES ';
             tit_abc_      = 'DECODED MILITARY ORIENTATION CODES ';

             tit_tsa       = 'TSA AREA ';
             tit_r         = 'R AREA ';

             tit_fl        = 'FLIGHT LEVELS ';

             tit_aip_in    = 'DOMESTICS AIRPORTS ';
             tit_aip_out   = 'FOREIGN AIRPORTS ';
           {$ENDIF}

