(*-------------------------------------------------------------------*)
(* LETVIS FDP - texty                                                *)
(* (c) Ales Kosice 1995  (ab)                                        *)
(*-------------------------------------------------------------------*)
{$I comp.h}


unit FDP_msg;


interface


     uses TypeDef,
          keyb;

     {$I fdp_msg.h}
     {$I _FPLs_title.h}
     {$I ..\lib\mnu\_rtemnu.h}
     {$I ..\lib\mnu\_fdp.h}

     const  tit_ERROR_OB  = '-> ';


implementation

end.