          { I toto sa da includovat po castiach ako menu, co by buo cistejsie
          }

   const   hlp_UPG                = 'UPGRADE/'+exe;
           hlp_GUI                = 'MMI/'+exe;
           hlp_CFG                = 'CFG';

           hlp_ask                = 'ASK';            {?}
           hlp_index              = 'INDEX';          {?}
           hlp_formular           = 'FORM';
           hlp_editor             = 'EDITOR';         {?}
           hlp_zoznam             = 'LISTING';


         { Plany
         }
           hlp_FPLi_vyber         = 'FPLI-SELECT';
           hlp_PREHLAD_FPLi       = 'FPLI-LIST';


           hlpmnuRPL              = 'RPL-FUNCTIONS';
           hlp_PREHLAD_RPL        = 'RPL-LIST';
           hlp_PREHLAD_RPL_ERR    = 'RPL-LIST-ERR';
           hlp_mnu_RPL_NASTAV     = 'RPL-OPTIONS';
           hlp_RPL                = 'RPL-PLAN';
           hlp_RPL_DB             = 'RPL-DB';


           hlpmnuPLN              = 'PLN-FUNCTIONS';
           hlp_PREHLAD_PLN        = 'PLN-LIST';
           hlp_mnu_PLN_NASTAV     = 'PLN-OPTIONS';
           hlp_PLN                = 'PLN-PLAN';


           hlpmnuFPL4             = 'FPL4-FUNCTIONS';
           hlpmnuFPL4i            = 'FPL4-FUNCTIONS/I';
           hlp_PREHLAD_FPL4       = 'FPL4-LIST';
           hlp_mnu_PREHLAD_FPL4D  = 'FPL4D-LISTS';
           hlp_mnu_FPL4_NASTAV    = 'FPL4-OPTIONS';
            hlp_mnu_FPL4_SPRACOVANIE = 'FPL4-PROCESS';
            hlp_mnu_FPL4_ZOBRAZENIE  = 'FPL4-DISPLAY';
            hlp_mnu_FPL4_DEKODOVANIE = 'FPL4-DECODE';
            hlp_mnu_FPL4_EDITOVANIE  = 'FPL4-FILL-IN';
           hlp_FPL4               = 'FPL4-PLAN';


           hlpmnuFPLC             = 'FPLC-FUNCTIONS';
           hlpmnuFPLCi            = 'FPLC-FUNCTIONS/I';
           hlp_mnu_FPLC_NASTAV    = 'FPLC-OPTIONS';
           hlp_PREHLAD_cFPL       = 'FPLC-LIST';
            hlp_cFPL              = 'FPLC-PLAN';
            hlp_cFPL_vyp          = 'FPLC-EST';
            hlp_STA_FPLC          = 'FPLC-STA';
            hlp_cFPL_FLI          = 'FPLC-FLI';


           hlpmnuFPLM             = 'FPLM-FUNCTIONS';
           hlpmnuFPLMi            = 'FPLM-FUNCTIONS/I';
           hlp_mnu_FPLM_FUNC_APP  = 'FPLM-FUNCTIONS/'+exe;
           hlp_mnu_FPLM_NASTAV    = 'FPLM-OPTIONS';
           hlp_PREHLAD_mFPL       = 'FPLM-LIST';
           hlp_PREHLAD_oFPL       = 'FPLO-LIST';
            hlp_mFPL              = 'FPLM-PLAN';
            hlp_mFPL_vyp          = 'FPLM-EST';
            hlp_mFPL_trat         = 'FPLM-ROUTE';
            hlp_mFPL_CHG          = 'FPLM-CHG';
            hlp_mFPL_CNL          = 'FPLM-CNL';
            hlp_mFPL_REQ          = 'FPLM-REQ';
            hlp_mFPL_DEP          = 'FPLM-DEP';
            hlp_mFPL_MZP          = 'FPLM-MZP';
            hlp_mFPL_RTE          = 'FPLM-RTE';
            hlp_mFPL_ARR          = 'FPLM-ARR';

           hlpmnuKRL              = 'FPLM-KRL-FUNCTIONS';
           hlp_mnu_KRL_FUNC_APP   = 'FPLM-KRL-FUNCTIONS/'+exe;
           hlp_mnu_KRL_NASTAV     = 'FPLM-KRL-OPTIONS';


           hlpmnuZAM              = 'ZAM-FUNCTIONS';
            hlp_mnu_ZAM_NASTAV    = 'ZAM-OPTIONS';
            hlp_ZAM               = 'ZAM-PLAN';


           hlpmnuQGO              = 'QGO-FUNCTIONS';
            hlp_mnu_QGO_NASTAV    = 'QGO-OPTIONS';
            hlp_QGO               = 'QGO-PLAN';

           hlpmnuRTZ              = 'RTZ-FUNCTIONS';
            hlp_mnu_RTZ_NASTAV    = 'RTZ-OPTIONS';
            hlp_RTZ               = 'RTZ-PLAN';


           hlpmnuDVZ              = 'DVZ-FUNCTIONS';
            hlp_mnu_DVZ_NASTAV    = 'DVZ-OPTIONS';
            hlp_DVZ               = 'DVZ-PLAN';


           hlpmnuPRZ              = 'PRZ-FUNCTIONS';
            hlp_mnu_PRZ_NASTAV    = 'PRZ-OPTIONS';
            hlp_PRZ               = 'PRZ-PLAN';


           hlpmnuPRS              = 'PRS-FUNCTIONS';
           hlpmnuPRSi             = 'PRS-FUNCTIONS/I';
            hlp_mnu_PRS_NASTAV    = 'PRS-OPTIONS';
            hlp_PRS               = 'PRS-PLAN';


           hlp_AUP                = 'FUA-PLAN';
           hlp_UUP                = 'FUA-PLAN';


           hlpmnuMET              = 'MET-FUNCTIONS';
            hlp_mnu_MET_NASTAV    = 'MET-OPTIONS';

           hlpmnuSPR              = 'MSG-FUNCTIONS';
            hlp_mnu_SPR_NASTAV    = 'MSG-OPTIONS';
            hlp_PREHLAD_spravy    = 'MSG-LIST';
            hlp_SPR               = 'MSG-PLAN';

           hlpmnuTLG              = 'TLG-FUNCTIONS';
            hlp_mnu_TLG_NASTAV    = 'TLG-OPTIONS';
            hlp_PREHLAD_TLG       = 'TLG-LIST';
            hlp_TLG               = 'TLG-PLAN';


           hlpmnuSSR              = 'SSR-FUNCTIONS';
            hlp_mnu_SSR_NASTAV    = 'SSR-OPTIONS';
            hlp_SSR_ASSIGN        = 'SSR-ASSIGN';
            hlp_SSR_ERROR         = 'SSR-ERROR';


         { Prehlady
         }
           hlpmnuPREHLAD          = 'DATA';
           hlpmnuAIP              = 'AIP-FUNCTIONS';


         { Nastavenia
         }
           hlpmnuSYSTEM           = 'SYSTEM';
           hlpmnuSYSTEM_UTC       = 'SYSTEM-UTC';
           hlpmnuSYSTEM_PRN       = 'SYSTEM-PRN';
           hlpmnuSYSTEM_NETWORK   = 'SYSTEM-NETWORK';

           hlpmnuSYSTEM_NET       = 'SYSTEM-NET';
           hlpmnuSYSTEM_NET_LAST  = 'SYSTEM-NET-LAST';
           hlpmnuSYSTEM_NET_INIT  = 'SYSTEM-NET-INIT';
           hlpmnuSYSTEM_NET_OPT   = 'SYSTEM-NET-OPTIONS';

           hlpmnuSYSTEM_EXT_ON    = 'SYSTEM-EXT-ON';
           hlpmnuSYSTEM_EXT_OPT   = 'SYSTEM-EXT-OPT';
           hlpmnuSYSTEM_EXT_COM   = 'SYSTEM-EXT-COM';

           hlpmnuSYSTEM_EXT_AFTN  = 'SYSTEM-EXT-AFTN';
           hlpmnuSYSTEM_EXT_CAMUS = 'SYSTEM-EXT-CAMUS';
           hlpmnuSYSTEM_EXT_OPL   = 'SYSTEM-EXT-OPL';
           hlpmnuSYSTEM_EXT_ASOC  = 'SYSTEM-EXT-ASOC';

           hlpmnuSYSTEM_VYPIS     = 'SYSTEM-STREAM-LIST';
           hlpmnuSYSTEM_ARCH      = 'SYSTEM-STREAM-ARCH';


           hlpmnuMMI              = 'MMI-FUNCTIONS';
           hlpmnuMMI_ZOZNAMY      = 'MMI-ZOZNAMY';
           hlpmnuMMI_OPTIONS      = 'MMI-OPTIONS';
           hlpmnuMMI_OPTIONS_DATA = 'MMI-OPTIONS-DATA';

           hlpmnuMMI_MAPS         = 'MMI-MAPS';
           hlpmnuMMI_MAPS_CENTRE  = 'MMI-MAPS-CENTRE';
           hlpmnuMMI_MAPS_RANGE   = 'MMI-MAPS-RANGE';
           hlpmnuMMI_MAPS_DRAW    = 'MMI-MAPS-DRAW';


           {hlpmnuDATA_DECODE      = 'DATA-DECODE';}
           hlpmnuOPTIONS          = 'OPTIONS';


         { EDD
         }
           hlpmnuPROPOSED_DATA    = 'PROPOSED-DATA';
           hlpmnuACCEPTED_DATA    = 'ACCEPTED-DATA';

           hlpmnuPROPOSED_STRIP   = 'PROPOSED-STRIP';
           hlpmnuACCEPTED_STRIP   = 'ACCEPTED-STRIP';


           hlpmnuBOARD            = 'BOARD-FUNCTIONS';
           hlpmnuBOARD_PROPOSED   = 'BOARD-PROPOSED';
           hlpmnuBOARD_ARRANGE    = 'BOARD-ARRANGE';
           hlpmnuBOARD_SORT       = 'BOARD-SORT';
           hlpmnuBOARD_DIFFER     = 'BOARD-DIFFER';
           hlpmnuBOARD_DISPLAY    = 'BOARD-DISPLAY';
           hlpmnuBOARD_PRINT      = 'BOARD-PRINT';

           hlpmnuBOARD_FORMAT     = 'BOARD-FORMAT';
           hlpmnuBOARD_EDIT       = 'BOARD-EDIT';
           hlpmnuBOARD_GROUPS     = 'BOARD-GROUPS';


           hlpmnuESTfunc          = 'EST-FUNCTIONS';
           hlpmnuACT              = 'ACT';
           hlpmnuEST              = 'EST';
           hlpmnuETO              = 'ETO';
           hlpmnuCNL              = 'CNL';
           hlpmnuSEARCH           = 'SEARCH';
           hlpmnuVIEW             = 'VIEW';
           hlpmnuARCHIV           = 'ARCHIV';
           hlpmnuAREA             = 'AREA';


         { OPL
         }


         { Funkcie programu
         }
           hlp_STA                = 'STA/'+exe;

