
      {$IFDEF SLOVAK}
        const tit_MAP_CENTR = '~'#17#196#217'~ - vystredenie mapy   ~Esc~ - vystreden  mapa';
      {$ENDIF}

      {$IFDEF CZECH}
        const tit_MAP_CENTR = '~'#17#196#217'~ - vyst©eden¡ mapy   ~Esc~ - vyst©edˆn  mapa';
      {$ENDIF}

      {$IFDEF ENGLISH}
        const tit_MAP_CENTR = '~'#17#196#217'~ - centering         ~Esc~ - confirmation';
      {$ENDIF}

