            {$IFDEF SLOVAK}
      const  tit_priebezna_statistika  = ' Priebeën† ®tatistika za ';
             tit_uzatvorena_statistika = ' Uzatvoren† ®tatistika za ';

             tit_uzatvorenie_dennej_statistiky   = 'Uzatv†ra sa denn† ®tatistika.';
             tit_uzatvorenie_mesacnej_statistiky = 'Uzatv†ra sa mesaán† ®tatistika.';


             mnu_STATISTIKA            = ' ~õ~TATISTIKA ';
             mnu_PRIEBEZNA_STATISTIKA  = ' PRIEBEíNè ~õ~TATISTIKA';
             mnu_UZATVORENA_STATISTIKA = ' UZATVORENè õ~T~ATISTIKA';
             mnu_DENNA_STATISTIKA      = ' ~D~ENNè õTATISTIKA ';
             mnu_MESACNA_STATISTIKA    = ' ~M~ESAÄNè õTATISTIKA ';

             err_AKTUALIZACIA_NEDOVOLENA  = 50;
            {$ENDIF}


            {$IFDEF CZECH}
            XX
      const  tit_priebezna_statistika  = ' Priebeën† ®tatistika za ';
             tit_uzatvorena_statistika = ' Uzatvoren† ®tatistika za ';

             tit_STATISTIKA            = ' ~õ~TATISTIKA ';
             tit_PRIEBEZNA_STATISTIKA  = ' PRIEBEíNè ~õ~TATISTIKA';
             tit_UZATVORENA_STATISTIKA = ' UZATVORENè õ~T~ATISTIKA';
             tit_DENNA_STATISTIKA      = ' ~D~ENNè õTATISTIKA ';
             tit_MESACNA_STATISTIKA    = ' ~M~ESAÄNè õTATISTIKA ';
            {$ENDIF}


            {$IFDEF ENGLISH}
      const  tit_priebezna_statistika  = ' Priebeën† ®tatistika za ';
             tit_uzatvorena_statistika = ' Uzatvoren† ®tatistika za ';

             tit_uzatvorenie_dennej_statistiky   = 'Uzatv†ra sa denn† ®tatistika.';
             tit_uzatvorenie_mesacnej_statistiky = 'Uzatv†ra sa mesaán† ®tatistika.';


             mnu_STATISTIKA            = ' ~õ~TATISTIKA ';
             mnu_PRIEBEZNA_STATISTIKA  = ' PRIEBEíNè ~õ~TATISTIKA';
             mnu_UZATVORENA_STATISTIKA = ' UZATVORENè õ~T~ATISTIKA';
             mnu_DENNA_STATISTIKA      = ' ~D~ENNè õTATISTIKA ';
             mnu_MESACNA_STATISTIKA    = ' ~M~ESAÄNè õTATISTIKA ';

             err_AKTUALIZACIA_NEDOVOLENA  = 50;
            {$ENDIF}
