; -----------------------------------------------
; Nastavenie pripojenia ku AFTN pre :
; תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת
; AMC Bratislava  (LETVIS FDP/OPL)
; -----------------------------------------------


;----------------------------
; NODES IDENTIFICATION
;תתתתתתתתתתתתתתתתתתתתתתתתתתתת

  FIR            = LZIB                ; FIR code

  THIS NODE      = LZBBZDZX            ; self AFTN address
; ALIAS NODE     =                     ; another AFTN acceptable adresses
  REMOTE NODE    = *                   ; adress of accepted sources/senders -> all


;----------------------------
; AFTN LINE SETTING
;תתתתתתתתתתתתתתתתתתתתתתתתתתתת

  INPUT ADDRESS  = LZBBZDZX
  OUTPUT ADDRESS = LZBBZDZX

  INPUT CHANNEL  = VLA                 ; [1]
  OUTPUT CHANNEL = LVA


; תתתתתתתתתתתתת
; RS232 setup :
; תתתתתתתתתתתתת

  COM         = 2
  MODE        = 1200
  BITS        = 5
  STOP_BITS   = 2
  PARITY      = NONE


; תתתתתתתתתתתתת
; AFTN setup  :
; תתתתתתתתתתתתת

  Ts_TimeOut  = 20                     ; TimeOut [min] for sended messages
  Tr_TimeOut  = 20                     ; TimeOut [min] for received messages

  HeartBeat ID       = CH LR
  HeartBeat PERIODE  = 2
  HeartBeat MIN      = 1

  STREAM SAVE = no                     ; archive binary AFTN data


;-----------------------------
; AFTN MESSAGES PROCESSING
;תתתתתתתתתתתתתתתתתתתתתתתתתתתתת

  LIMIT - TLG CONFIRM = 24
  LIMIT - ERR PROCESS = 24


