; --------------------------------
; ine udaje
; תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת

 OBSOLETE PRIORITY    = yes   ; povodne vytvorene mapy s neoptimalizovanymi prioritami
 DRAW MARKED SYMBOLS  = yes   ; symboly sa nacitaju len z popisanych sybolov


; -----------------------------------------------------
; aktualizacia map     ; meno_subora/symbol,symbol...
; תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת

  SYMBOL FILE = AIP-C
  SYMBOL FILE = AIP-M  ; AIP-M/AIP-M  
  SYMBOL FILE = AIP-A  ; AIP-A/AIP-A

  SYMBOL FILE = NDB
  SYMBOL FILE = NDB-MIL; OB


; ---------------------------------------------
; symboly s nastavitelnym zobrazenim poloziek
; תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת

  SYMBOL MENU = AIP-C
  SYMBOL MENU = AIP-M
  SYMBOL MENU = AIP-A
  SYMBOL MENU =         ; prazdny riadok v menu
  SYMBOL MENU = NDB
  SYMBOL MENU = OB


; --------------------------------
; farby symbolov (odtiene sivej)
; תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת

  AIP-C     = 27
  AIP-M     = 27
  AIP-A     = 24

  OB        = 24

  SP        = 22
  REP1      = 22
  REP2      = 22
  NDB1      = 22
  NDB2      = 22
  VOR       = 22
  VOR/DME1  = 22
  VOR/DME2  = 22


; --------------------------------
; farby map
; תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת

; BDRY F    = 38
; BDRY      = 23

; AWY F     = 35
; AWY       = 21

; TMA F     = 36
; TMA       = 37

; CTR F     = 38
; CTR       = 38

; ACT A     = 40
; ACT P     = 41

; R F       = 45
; R A       = 46

; TSA A     = 46
; TSA P     = 47

; PRS A     = 48
; PRS P     = 49

; R F       = 4
; R A       = 4

; ILS       = 22
; RTE       = 22

; PAV0      = 19
; PAV1      = 20
; PAV2      = 20

  LDM0      = 23
  LDM1      = 21
  LDM2      = 20

; MARK      = 24


; DESC      = 14


; GRP_ACT_   = 0   ;    { potlacenie olemovanie aktivovanych priestorov }
