; -----------------------------------------------------
;  N†zvy a parametre pre sledovanÇ ®tatistickÇ hodnoty
; -----------------------------------------------------

;----------------------
; hlavicka pre SRLP
;----------------------

 header-macc      = õtatistika realizovanòch letov
 header-macc      = za %DATE%
 header-macc      = SRLP Bratislava
 header-macc      =


;---------------------
; hlavicka pre LSRLP
;---------------------

 header-airbase   = õtatistika realizovanòch letov a vyuëitia priestorov
 header-airbase   = za %DATE%
 header-airbase   = na LSRLP %AIRBASE%
 header-airbase   =


;----------------------------
; spolocne nazvy udajov
;----------------------------

 title-suma       = SPOLU

 title-airbases   = LETISKè
 title-airbase    = LSRLP


;-------------------------------
; sledovane udaje o letoch

;parametre

 FPLC-FL = S0745
 FPLM-FL = S0745
 FPLO-FL = M0300


;------------------
; SRLP
;------------------

 title-realized-flights = REALIZOVANê LETY LSRLP
 title-military-flights = LETY RIADENê SRLP (vojenskÇ a inÇ)
 title-civilian-flights = LETY RIADENê ACC  (po tratiach LPS)

;title-FPLM       = FPL
 title-FPLM-FL    = Ú%FPLM-FL%
 title-FPLM-VFR   = VFR
 title-FPLM-IFR   = IFR
 title-FPLM-TSA   = TSA

 title-FPLO       = INê

 title-FPLC-VFR   = VFR
 title-FPLC-IFR   = IFR
 title-FPLC-FL    = Ú%FPLC-FL%


;------------------
; LSRLP
;------------------

;-----------------------------
; statistika letov za mesiac

 title-realized-flights-A = õTATISTIKA PLèNOVANùCH LETOV
 title-total-flights-A    = CELKOVù POÄET ODRIADENùCH LETOV
 title-flight-type-A      = Typ letov

;title-FPLM-A     = VojenskÇ lety
 title-FPLM-VFR-A = TraüovÇ lety VFR
 title-FPLM-IFR-A = TraüovÇ lety IFR
 title-FPLM-FL-A  = TraüovÇ lety nad %FPLM-FL%
 title-FPLM-TSA-A = Lety do TSA                    ;  vòcvikovòch priestorov
 title-FPLM-ZAM-A = LetiskovÇ lety

 title-FPLO-A     = InÇ lety (nevojenskÇ)

 title-FPLC-A     = CivilnÇ lety
 title-FPLC-FL-A  = CivilnÇ lety nad %FPLC-FL%

 title-planned    = Pl†novanÇ
 title-realized   = UskutoánenÇ
 title-controlled = RiadenÇ


;--------------------------------
; statistika vyzitia priestorov

 title-tsa-area       = PRIESTORY LZR a TSA
 title-gnd-area       = STRELNICE POZEMNêHO VOJSKA

 title-area           = Priestor

 title-tsa-reserved   = Pl†n
 title-tsa-used       = VyuëitÇ
 title-tsa-flights    = Letov

 title-gnd-reserved   = Poáet objednanòch dn°
 title-gnd-used       = Poáet vyuëitòch dn°

;poradie vypisu sledovanych priestorov

 line-area = R13
 line-area = R22
 line-area = R24
 line-area = R80
 line-area = R84
 line-area = R86
 line-area = TSA01
 line-area = TSA02A
 line-area = TSA02B
 line-area = TSA02C
 line-area = TSA03
 line-area = TSA04
 line-area = TSA05A
 line-area = TSA05B
 line-area = TSA06A
 line-area = TSA06B
 line-area = TSA06C
 line-area = TSA07A
 line-area = TSA07B
 line-area = TSA08A
 line-area = TSA08B
 line-area = TSA09A
 line-area = TSA09B
 line-area = TSA09C
 line-area = TSA09D
 line-area = TSA10A
 line-area = TSA10B
 line-area = TSA11A
 line-area = TSA11B

