;-----------------------
; FIR DESCRIBTION
;תתתתתתתתתתתתתתתתתתתתתתת

 AIRBASE = 500


;-----------------------
; SSR MANAGEMENT
;תתתתתתתתתתתתתתתתתתתתתתת

; SSR = 6116-6130


;-----------------------
; FUNCTIONS
;תתתתתתתתתתתתתתתתתתתתתתת

 edit FPLm = yes ; povolenie editacie vojenskeho a ineho stripu
 edit FPLc = no  ; povolenie editacie civilneho stripu


;-----------------------
; SYSTEM
;תתתתתתתתתתתתתתתתתתתתתתת

 time = 1
 db-rw-close = no


;-----------------------
; NET
;תתתתתתתתתתתתתתתתתתתתתתת

 net-init-timeout = 30


;-----------------------
; INE
;תתתתתתתתתתתתתתתתתתתתתתת

 exception-call-desc = false
