; -----------------------------------------
;  FDP/OPL - SMD/AMC
; =========================================

; --------------------------------------------------------------------------------------------------------------------------------
; Pracovisko ; Adresa logicka,   RTR, IP        ; Protokol ; Stanica  ; informacie                               ; ine nastavenia
; --------------------------------------------------------------------------------------------------------------------------------

; ----------------------------
; VS
; ----------------------------

  SERVER     ; StrRLP SERVER ,  192.100.100.101 ; ~UDP ~L  ; @SERVER  ; -master     MSG  ALL \KRL \SYN ; timeout=10
  RTZ        ; StrRLP RTZ    ,  192.100.100.102 ; ~UDP ~L  ; @BSERVER ; -backup     MSG  ALL \KRL \SYN ; timeout=10

  AMC_VC     ; VS AMC        ,  192.100.100.17  ; @THIS
  DPVL       ; VS DPVL       ,  192.100.000.33  ; ~UDP ~L  ; @IDD     ;  MSG      ; timeout=10


; ----------------------------
; SRLP
; ----------------------------
; BRIDGE     ; StrRLP BRIDGE ,   192.100.141.35 ; ~UDP  L  ; @BRIDGE  ;   MSG

  SMD        ; StrRLP SMD    ,   192.100.141.41 ; ~UDP ~L  ; @OPL     ;   MSG  ; timeout=10
  SOD        ; StrRLP SOD    ,   192.100.141.42 ; ~UDP ~L  ; @OPL     ;   MSG  ; timeout=10


; ----------------------------
; SAR
; ----------------------------
  SAR        ; SAR OPL       ,   192.100.143.32 ; ~UDP ~L  ; @OPL     ;   MSG  ; timeout=10


; ----------------------------
; VLIS
; ----------------------------
; VLIS       ; VLIS          ,   192.100.142.06 ; ~UDP ~L  ; @LIS     ; MSG ; timeout=10


; ----------------------------
; Letiska
; ----------------------------
  100        ; 100 OPL       ,   192.100.037.32 ; ~UDP ~L  ; @OPL     ;  -ap MSG  ; timeout=10
  200        ; 200 OPL       ,   192.100.145.32 ; ~UDP ~L  ; @OPL     ;  -ap MSG  ; timeout=10
  250        ; 250 OPL       ,   192.100.011.32 ; ~UDP ~L  ; @OPL     ;  -ap MSG  ; timeout=10
  300        ; 300 OPL       ,   192.100.073.32 ; ~UDP ~L  ; @OPL     ;  -ap MSG  ; timeout=10
  500        ; 500 OPL       ,   192.100.113.32 ; ~UDP ~L  ; @OPL     ;  -ap MSG  ; timeout=10
  600        ; 600 OPL       ,   192.100.107.32 ; ~UDP ~L  ; @OPL     ;  -ap MSG  ; timeout=10


; ----------------------------
; RDC
; ----------------------------
  100_RDC    ; 100 RDC       ,   192.100.040.32 ; ~UDP ~L  ; @IDD     ;  MSG   ; timeout=10
  250_RDC    ; 250 RDC       ,   192.100.013.33 ; ~UDP ~L  ; @IDD     ;  MSG   ; timeout=10
  300_RDC    ; 300 RDC       ,   192.100.073.32 ; ~UDP ~L  ; @IDD     ;  MSG   ; timeout=10
  500_RDC    ; 500 RDC       ,   192.100.111.32 ; ~UDP ~L  ; @IDD     ;  MSG   ; timeout=10
  600_RDC    ; 600 RDC       ,   192.100.105.32 ; ~UDP ~L  ; @IDD     ;  MSG   ; timeout=10

