 { -----------------
   INSTALACIA
   -----------------
 }
  {$DEFINE RLP}

  {$DEFINE MATCA}    { MILITARY_ATC_AUTHORITY }
  {$DEFINE AIRBASE}
  {$DEFINE TWR}
  {$DEFINE A-A}      { AIRSPACE USER }


 { -----------------
   SPRACOVAVANE DATA
   -----------------
 }
  {$DEFINE PPL}
  {$DEFINE FPL}
  {$DEFINE FPL0}

  {$DEFINE FPLM_L}          { velke FPL }
  {$DEFINE FPLO}
    {$DEFINE FPLM_PLAN}
    {$DEFINE PROCESS_FPLM}
    {$DEFINE FPLM_REPORT}
    { DEFINE FPLM_REGULARITA}
    {$DEFINE REPORT_FPLM_ARW}

  {$DEFINE KRL}
    {$DEFINE PROCESS_KRL}

  {$DEFINE ZAM}
    {$DEFINE ZAM_PLAN}       { zatial nema zmysel }
    {$DEFINE PROCESS_ZAM}
    {$DEFINE ZAM_REPORT}

  {$DEFINE QGO}
    {$DEFINE QGO_PLAN}       { zatial nema zmysel }
    {$DEFINE PROCESS_QGO}
    {$DEFINE QGO_REPORT}

  {$DEFINE DVZ}
    {$DEFINE PROCESS_DVZ}
    {$DEFINE DVZ_REPORT}


  {$DEFINE NOTAM}
    {$DEFINE NOTAM_REPORT}

  {$DEFINE PRZ}
    {$DEFINE PRZ_PLAN}
    {$DEFINE PRZ_REQUEST}
    {$DEFINE PRZ_REPORT}

  {$DEFINE PRS}
    {$DEFINE PRS_L}
    {$DEFINE PRS_PLAN}
    {$DEFINE PROCESS_PRS}
    {$DEFINE PRS_REPORT}
    { DEFINE PRS_REGULARITA}

    {$DEFINE FUA}
      {$DEFINE FUA_DATA}


  {$DEFINE MET}

  {$DEFINE SPR}
    {$DEFINE SPR_L}



 { -----------------
   FUNKCIE
   -----------------
 }
  {$DEFINE MACC_MENU}

  {$DEFINE RDP}
    { DEFINE RDP_ACCEPT}

  { DEFINE STATISTIKA_OPL}
    { DEFINE STATISTIKA_CLIENT}
    { DEFINE STATISTIKA}



 { -----------------
   KOMUNIKACIA
   -----------------
 }
  {$DEFINE NET}

  (*{$DEFINE COM}
  {$DEFINE IPX}

  {$DEFINE X25}
    {$DEFINE AdCOM2}  { DEFINE _X25_CONNECT_TIME_OUT}
  *)

  {$DEFINE PCTCP}
    {$DEFINE UDP}
