; -------------------------------------------------
; Komunikacny uzol medzi LETVIS a OPL / MACC Praha
; Zapojenie na TS MACC
;
; -------------------------------------------------


;---------------
; ADRESY
;תתתתתתתתתתתתתתת

  FIR         = LK
  THIS NODE   = MI
  REMOTE NODE = PL



;---------------
; COM PORT
;תתתתתתתתתתתתתתת

  COM         = 1
  MODE        = 9600
  BITS        = 7
  STOP_BITS   = 1
  PARITY      = EVEN



;---------------
; Komunikacia
;תתתתתתתתתתתתתתת

  Ts_TimeOut  = 40
  Ts_TimeOut  = 40



;---------------
; Spracovanie
;תתתתתתתתתתתתתתת

  SEND VFR FPL      = yes
  FL FROM ALTITUDE  = no

