;-----------------------
; FIR DESCRIBTION
;תתתתתתתתתתתתתתתתתתתתתתת

  AIRBASE = UKBB


;-----------------------
; SSR MANAGEMENT
;תתתתתתתתתתתתתתתתתתתתתתת

  SSR = 6116-6130


;-----------------------
; SYSTEM
;תתתתתתתתתתתתתתתתתתתתתתת

;  win.tmp = E:\
  time = 1

