; -----------------------------------------------
; NET configuration for FDP ACC Kiev
; ===============================================

; -----------------------------------------------------------------------------------------------------------------------
; Workplace Name            ; Address : Logical, RTR, IP    ; Protocol ; Workstation  ; Information
; -----------------------------------------------------------------------------------------------------------------------

; -------------------------
; SERVER positions
; -------------------------

  server AFTN [P1]          ; S1      , $0032               ; ~RTI  ~L ; @FDP @SERVER ; -master  AFTN PLN FPL4 EST FPLM FPLO
  server AFTN [P2]          ; S2      , $0033,              ; @THIS

  server PRN  [BGU/MPU]     ; PRN     , $0034               ; ~RTI     ; @FDP @EDD    ;


; -------------------------
; EDD/RDP positions
; -------------------------

  K4 EDD - KIEV APP         ; K4      , $0006,              ; ~RTI  L ; @FDP @EDD    ; -slave  PL4 EST FPLM FPLO
  K3 EDD - LVOV             ; K3      , $0008,              ; ~RTI  L ; @FDP @EDD    ; -slave  PL4 EST FPLM FPLO
  K1 EDD - MOSKVA,KHARKIV   ; K1      , $000B,              ; ~RTI  L ; @FDP @EDD    ; -slave  PL4 EST FPLM FPLO
  K2 EDD - ODESSA,DNEPRO... ; K2      , $0010,              ; ~RTI  L ; @FDP @EDD    ; -slave  PL4 EST FPLM FPLO

  P1 EDD                    ; P1      , $000D,              ; ~RTI  ~L ; @FDP @EDD   ; -slave  FPL4 EST FPLM FPLO
  P2 EDD                    ; P2      , $0012,              ; ~RTI  ~L ; @FDP @EDD   ; -slave  FPL4 EST FPLM FPLO

  MIL EDD                   ; MIL     , $0014,              ; ~RTI  ~L ; @FDP @EDD   ; -slave  FPL4 EST FPLM FPLO

  TS RDP                    ; TS_RDP  , $0015,              ; ~RTI     ; @RDP        ; -slave       EST FPLM FPLO