
    const  IA5_SOH                  = #1;
           IA5_STX                  = #2;
           IA5_ETX                  = #3;

           IA5_CR                   = #13;
           IA5_LF                   = #10;
           IA5_NL                   = IA5_CR+IA5_LF;

           IA5_VT                   = #11;

           IA5_SPACE                = #32;
           IA5_BEEP                 = #7;


    const  IA5_CHANNEL_SIZE         = 3;
