    function   prienik_vysok (vys1s,vys1h, vys2s,vys2h: string): bool;

    function  _check_rychvys_by4444 (kod: string; typ : string;
                                     var rych: single; var rych_: char;
                                     var vys: word; var vys_: char;
                                     var res: string
                                    ): int;

    function  _check_rychvys2_by4444 (kod : string; typ : string;
                                      var rych: single; var rych_: char;
                                      var vys: word; var vys_,vys_a: char;
                                      var vys2: word; var vys2_: char;
                                      var res: string
                                     ): int;
