    const  OLDIcfg           = 'OLDI'+ext_ini;

           cfg_X25adr_THIS   = 'THIS X25';
           cfg_X25adr_MASTER = 'MASTER X25';
           cfg_X25adr_BACKUP = 'BACKUP X25';

           cfg_NSAP_THIS     = 'THIS NSAP';
           cfg_NSAP_REMOTE   = 'REMOTE NSAP';

           cfg_Send_StartUp  = 'SEND-STARTUP';
           cfg_switch_Remote = 'SWITCH-REMOTE';


    const  OLDI_pkt_size_lo  =  128;
           OLDI_pkt_size_hi  = 4096;

           OLDI_pkt_size     =  512;

