     const SPUNRESF 	= 53;
	   SPINITF 	= 1;
	   SPENDF	= 6;
	   SPLDFNTF	= 99;
	   SPSTFNTF	= 96;
	   SPSLFNTF	= 98;
	   SPRMFNTF  	= 95;
	   SPENFNTF	= 97;

	   SPINFOF 	= 2;
	   SPIPAGEF 	= 3;
	   SPICOLF 	= 4;
	   SPIFONTF 	= 5;

	   SPCCOLF 	= 11;
	   SPBCOLF 	= 12;
	   SPOPMODF 	= 13;
	   SPLSTYLF 	= 15;
	   SPSVLUF 	= 16;
	   SPGVLUF	= 91;
	   SPRVLUF	= 90;
	   SPSELPGF 	= 17;
	   SPSHWPGF	= 18;
	   SPSPLITF	= 19;
	   SPSHOWF 	= 20;

	   SPCLIPF	= 21;
	   SPNCLIPF	= 22;
	   SPSLCARDF	= 23;

	   SPSPATTF 	= 38;
	   SPDPATTF 	= 138;

	   SPCLRF	= 31;
	   SPDOTF	= 32;
	   SPVECTF 	= 33;
	   SPPOLYF 	= 34;

	   SPFPOLYF 	= 434;

	   SPFILLF 	= 35;
	   SPPFILLF 	= 36;
	   SPTEXTF 	= 27;
	   SPTXTDF	= 45;
	   SPTXTOF	= 46;
	   SPCIRF 	= 39;

	   SPFCIRF 	= 439;

	   SPARCF  	= 40;
	   SPCOPYF 	= 41;
	   SPPAINTF 	= 42;
	   SPGDOTF 	= 43;
	   SPSDOTF 	= 44;
	   SPIRCURSF	= 54;
	   SPDRCURSF	= 55;
	   SPCRCURSF	= 56;

	   SPVSPOSF 	= 501;
	   SPVGPOSF 	= 502;
	   SPVSWINDF 	= 503;
	   SPVGWINDF 	= 504;
	   SPVZOOMF	= 505;
	   SPVGSIZEF 	= 506;
	   SPVDISPF	= 507;
	   SPVGDISPF	= 508;
	   SPVGZOOMF	= 509;

	   SPBOXSAVEF   = 77;
	   SPBOXINQF	= 78;
  	   SPBOXRESTF	= 79;
  	   SPBOXFREEF	= 80;
