  const   odd_CFG_EQ = '=';
          odd_CFG_NL = ';';

          _ON  = 'ON';
          _OFF = 'OFF';      cfg_OFF_ON: array[false..true] of string[3] = (_OFF,_ON);

          _YES = 'YES';
          _NO  = 'NO';

          _EN  = 'ENABLED';
          _DIS = 'DISABLED';

          _FALSE = 'FALSE';
          _TRUE  = 'TRUE';


        { adresare }
          cfgTMP_DIR         = 'DIR.TMP';

          cfg_pathSaveWin    = 'WIN.TMP';
          cfg_SaveWinMem     = 'WIN-MEM';

