; ------------------------------
; FDP/ACC  ACC Borispol
; ------------------------------

  SECTORS = .\MAPS\SECTORS.ACC
  SECTOR  = S1,S2

; -----------
; K1 MOSKVA
; תתתתתתתתתתת
  S1; SEC = 000-060 ;  ALT = 0 ; K1
  S2; SEC = 060-110 ;  ALT = 0 ; K1

; -----------
; K2 ODESSA
; תתתתתתתתתתת
  S3; SEC = 110-150 ;  ALT = 0 ; K2
  S4; SEC = 150-200 ;  ALT = 0 ; K2

; -----------
; K3 LVOV
; תתתתתתתתתתת
  S5; SEC = 200-325 ;  ALT = 0 ; K3

; -----------
; K4 APP
; תתתתתתתתתתת
  S6; SEC = 000-360 ; ALT = S0810-S5500 ; K4