
     const
           {$IFDEF SLOVAK}
             ask_zmazat_polozku   = 'Vymazaü pole ';
             ask_zmazat_formular  = 'Vymazaü v®etky polia formul†ra ?';
           {$ENDIF}


           {$IFDEF CZECH}
             ask_zmazat_polozku   = 'Vymazat pole ';
             ask_zmazat_formular  = 'Vymazat v®echky pole formul†©e ?';
           {$ENDIF}


           {$IFDEF ENGLISH}
             ask_zmazat_polozku   = 'Delete item ';
             ask_zmazat_formular  = 'Delete all arrays of the form ?';
           {$ENDIF}
