  { --------------------------------------- }
  { cfg pre server, kam rozosielat spravy   }
  { --------------------------------------- }

    const { odosielana informacia   }

            inf_FPL4  = 'FPL4';
            inf_PLN   = 'PLN';

            {inf_EST   = 'EST';
            inf_CPL   = 'CPL';}

            inf_FPLC  = 'FPLC';
            inf_FPLM  = 'FPLM';
            inf_FPLO  = 'FPLO';

            inf_KRL   = 'KRL';

            inf_ZAM   = 'ZAM';

            inf_QGO   = 'QGO';
            inf_RTZ   = 'RTZ';
            inf_DVZ   = 'DVZ';

            inf_PRZ   = 'PRZ';
            inf_PRN   = 'PRN';
            inf_PRS   = 'PRS';

            inf_VLIS  = 'VLIS';
            inf_FUA   = 'FUA';

            inf_SYN   = 'SYN';
            inf_MET   = 'MET';
            inf_MRL   = 'MRL';

            inf_SPR   = 'MSG';


            inf_AFTN  = 'AFTN';


  { --------------------------------------- }
  { ine konfiguracne priznaky               }
  { --------------------------------------- }

   const    info_FLI  = '~FLI';

   const    info_NODB = 'NODB';