     const   {$IFDEF SLOVAK}
               tit_INIT      = ' - Inicializ cia...';
               tit_DONE      = ' - Ukon‡en .';
               tit_INIT_DONE = ' - Inicializ cia £spe¨n .';
               tit_INIT_FAIL = ' - Inicializ cia ne£spe¨n .';
               tit_INIT_NOT  = ' - Inicializ cia zlyh va, bola vypnut . Uzol nebude inicializovanì do op„tovn‚ho nastavenia.';
               tit_UALWDATA  = 'Nie je dovolen‚ spracovanie spr v tohto typu od odosielaj£ceho uzla.';
             {$ENDIF}

             {$IFDEF CZECH}
               tit_INIT      = ' - Inicializace...';
               tit_DONE      = ' - Ukon‡en .';
               tit_INIT_DONE = ' - Inicializace probˆhla £spˆ¨nˆ.';
               tit_INIT_FAIL = ' - Inicializace nedokon‡ena.';
               tit_INIT_NOT  = ' - Inicializace selh va, byla vypnuta. Uzel nebude inicializov n do opØtovn‚ho nastaven¡.';
               tit_UALWDATA  = 'Nen¡ dovoleno zpracov n¡ zpr v tohto typu od odes¡laj¡ciho uzlu.';
             {$ENDIF}

             {$IFDEF ENGLISH}
               tit_INIT      = ' - Initializing... ';
               tit_DONE      = ' - Done.';
               tit_INIT_DONE = ' - Initialization has been succesfull.';
               tit_INIT_FAIL = ' - Initialization failed.';
               tit_INIT_NOT  = ' - Initalizing fails, it has been turned off. The node will not be initialized until set on.';
               tit_UALWDATA  = 'There is not allowed to processed this packet from this sender.';
             {$ENDIF}
