; -----------------------------------------------
; IPX configuration for FDP ACC Kiev
; ===============================================


  S1       ; A02436A065 = 7
  S2       ; A02436A064 = 8
  PRN      ; C054CCDF   = 9


; K4       ; C05ACCDF  = 5 ; @THIS      ; $6
; K4_RDP   ; C0C3CCDF  = 6

; K3       ; C03ECCDF  = 5 ; @THIS      ; $7
; K3_RDP   ; C035CCDF  = 6

  K1       ; C0D2CCDF  = 5 ; @THIS
  K1_RDP   ; C037CCDF  = 6

; P1       ; C03CCCDF  = 5 ; @THIS
; P1_RDP   ; C036CCDF  = 6

; K2       ; C0BACCDF  = 5 ; @THIS      ; $10
; K2_RDP   ; C03BCCDF  = 6

; P2       ; A024369FB5 = 5 ; @THIS     ; $12
; P2_RDP   ; C03BCCDF   = 6

  MIL      ; C055CCDF  = A              ; $14
; MIL_RDP  ; C0D1CCDF  = 6 ; @THIS
