     {$IFDEF SLOVAK}
       const  titLIST   = '~L~ist  ';
              titDECODE = '~D~ecode';

              titNDBVOR = '~N~DB/VOR   ';
              titATSrte = '~A~TS routes';
              titREGrte = '~R~egular routes';

              titRPL4   = '~R~PL   ';


              tit_FPL4_initialize = 'Initializing the FPL...';
              tit_FPL4_checking   = 'Checking the FPL syntax...';
              tit_FPL4_processing = 'Processing FPL of ';

              ask_FPL4_idn_chg_fr = 'Aircraft identification changed from ';
              ask_FPL4_idn_chg_to = ' to ';
              ask_FPL4_del_prev   = ' Cancel and delete previous plan ? If not plan will be processed as new one.';
     {$ENDIF}


     {$IFDEF CZECH}
       const  titLIST   = '~L~ist  ';
              titDECODE = '~D~ecode';

              titNDBVOR = '~N~DB/VOR   ';
              titATSrte = '~A~TS routes';
              titREGrte = '~R~egular routes';


              tit_FPL4_initialize = 'Initializing the FPL...';
              tit_FPL4_checking   = 'Checking the FPL syntax...';
              tit_FPL4_processing = 'Processing FPL of ';

              ask_FPL4_idn_chg_fr = 'Aircraft identification changed from ';
              ask_FPL4_idn_chg_to = ' to ';
              ask_FPL4_del_prev   = ' Cancel and delete previous plan ? If not plan will be processed as new one.';
     {$ENDIF}


     {$IFDEF ENGLISH}
       const  titLIST   = '~L~ist  ';
              titDECODE = '~D~ecode';

              titNDBVOR = '~N~DB/VOR   ';
              titATSrte = 'AT~S~ routes';
              titREGrte = '~R~egular routes';

              titRPL4   = '~R~PL   ';


              tit_FPL4_initialize = 'Initializing the FPL...';
              tit_FPL4_checking   = 'Checking the FPL syntax...';
              tit_FPL4_processing = 'Processing FPL of ';

              ask_FPL4_idn_chg_fr = 'Aircraft identification has been changed from ';
              ask_FPL4_idn_chg_to = ' to ';
              ask_FPL4_del_prev   = ' Cancel and delete previous plan ? If not plan will be processed as new one.';
     {$ENDIF}

