
            { -------------------------
               SLOVAK
              -------------------------
            }
             {$IFDEF SLOVAK}

              { menu
              }
               mnu_FPLM_F5        = ' ~F~PL  PODANIE PLèNU                 F5 ';
               mnu_FPLM_CHG       = ' ~C~HG  OPRAVA ';
               mnu_FPLM_CNL       = ' C~N~L  ZRUõENIE ';
              {$ifdef airbase}
               mnu_FPLM_REQ       = ' ~R~EQ  VYíIADANIE PRIPOMIENKY  Shift+F5 ';
              {$endif}
              {$ifdef macc}
               mnu_FPLM_REQ       = ' ~R~EQ  VYDANIE PRIPOMIENKY     Shift+F5 ';
               mnu_FPLM_REQ2      = ' R~E~Q/CHG  OPRAVA VYDANEJ PRIPOMIENKY ';
              {$endif}
               mnu_FPLM_DEP       = ' ~D~EP  SPRèVA O õTARTE ';
               mnu_FPLM_EST       = ' ~E~ST  SPRèVA O LETE ';
               mnu_FPLM_ETO       = ' R~T~E  AKTUALIZèCIA SPRèVY O LETE ';
               mnu_FPLM_MZP       = ' ~M~ZP  MEDZIPRISTèTIE/õTART PO MZP ';
               {mnu_FPLM_MZS      = ' MZ~S~  õTART PO MEDZIPRISTèTã ';}
               mnu_FPLM_ARR       = ' ~A~RR  SPRèVA O PRISTèTI ';

               mnu_FPLM_          = ' ~F~PL ';
               mnu_FPLM_CHG_      = ' ~C~HG ';
               mnu_FPLM_CNL_      = ' C~N~L ';
               mnu_FPLM_REQ_      = ' ~R~EQ ';
               mnu_FPLM_REQ2_     = ' R~E~Q/CHG ';
               mnu_FPLM_DEP_      = ' ~D~EP ';
               mnu_FPLM_EST_      = ' ~E~ST ';
               mnu_FPLM_ETO_      = ' R~T~E ';
               mnu_FPLM_MZP_      = ' ~M~ZP ';
               mnu_FPLM_MZS_      = ' MZ~S~ ';
               mnu_FPLM_ARR_      = ' ~A~RR ';


             { spracovanie a prehlad KRL
             }
               mnu_KRL_oprava     = ' ~O~PRAVA KRãDLA ';
               mnu_KRL_zrus       = ' ~Z~RUõENIE KRãDLA ';
               mnu_KRL_oba        = '(PODANêHO I PRIJATêHO) ';
               mnu_KRL_sprac      = ' ~S~PRACOVANIE KRãDLA NA FPL ';

               mnu_KRL_odos_      = ' O~D~OSLANIE NA ';
               mnu_KRL_oprava_    = ' ~O~PRAVA KRãDLA ';
               mnu_KRL_zrus_      = ' ~Z~RUõENIE KRãDLA ';
               mnu_KRL_sprac_     = ' ~S~PRACOVANIE KRãDLA ';
               mnu_KRL_z_FPL      = ' PODANIE FPL AKO ~K~RãDLA PRE ';

               tit_KRIDLA_NASE    = ' KRãDLA PRE V~L~ASTNê LETY ';
               tit_KRIDLA_INE     = ' KRãDLA PRE I~N~ê LETISKè ';
               tit_KRIDLA_VSETKY  = ' ~V~õETKY SPRACOVèVANê KRãDLA ';
             {$ENDIF}


            { -------------------------
               CZECH
              -------------------------
            }
             {$IFDEF CZECH}
             { menu
             }
               mnu_FPLM_F5  =    ' ~F~PL  PODèNã PLèNU               F5 ';
               mnu_FPLM_CHG =    ' ~C~HG  OPRAVA ';
               mnu_FPLM_CNL =    ' C~N~L  ZRUõENã ';
              {$ifdef airbase}
               mnu_FPLM_REQ =    ' ~R~EQ  VYíèDANã PûIPOMãNY ';
              {$endif}
              {$ifdef macc}
               mnu_FPLM_REQ =    ' ~R~EQ  VYDèNã PûIPOMãNKY   Shift+F5 ';
              {$endif}
               mnu_FPLM_DEP =    ' ~D~EP  ZPRèVA O STARTU ';
               mnu_FPLM_EST =    ' ~E~ST  ZPRèVA O LETU ';
               mnu_FPLM_ETO =    ' R~T~E  AKTUALIZACE ZPRèVY O LETU ';
               mnu_FPLM_MZP =    ' ~M~ZP  MEDZIPûISTèTã/START PO MZP ';
               {mnu_FPLM_MZS =   ' MZ~S~  õTART PO MEDZIPRISTèTã ';}
               mnu_FPLM_ARR =    ' ~A~RR  ZPRèVA O PûISTèTI ';

               mnu_FPLM_     =   ' ~F~PL ';
               mnu_FPLM_CHG_ =   ' ~C~HG ';
               mnu_FPLM_CNL_ =   ' C~N~L ';
               mnu_FPLM_REQ_ =   ' ~R~EQ ';
               mnu_FPLM_DEP_ =   ' ~D~EP ';
               mnu_FPLM_EST_ =   ' ~E~ST ';
               mnu_FPLM_ETO_ =   ' R~T~E ';
               mnu_FPLM_MZP_ =   ' ~M~ZP ';
               mnu_FPLM_MZS_ =   ' MZ~S~ ';
               mnu_FPLM_ARR_ =   ' ~A~RR ';


             { spracovanie a prehlad KRL
             }
               mnu_KRL_oprava  = ' ~O~PRAVA PODANêHO KRãDLA ';
               mnu_KRL_zrus    = ' ~Z~RUõENIE PODANêHO KRãDLA ';
               mnu_KRL_sprac   = ' ~S~PRACOVANIE PRIJATêHO KRãDLA ';

               mnu_KRL_odos_   = ' O~D~OSLANIE NA ';
               mnu_KRL_oprava_ = ' ~O~PRAVA KRãDLA ';
               mnu_KRL_zrus_   = ' ~Z~RUõENIE KRãDLA ';
               mnu_KRL_sprac_  = ' ~S~PRACOVANIE KRãDLA ';
             {$ENDIF}


            { -------------------------
               ENGLISH
              -------------------------
            }
             {$IFDEF ENGLISH}

              { menu
              }
               mnu_FPLM_F5        = ' ~F~PL  PLAN FILLING               F5 ';
               mnu_FPLM_CHG       = ' ~C~HG  PLAN CORRECTION ';
               mnu_FPLM_CNL       = ' C~N~L  PLAN CANCELATION ';
              {$ifdef airbase}
               mnu_FPLM_REQ       = ' ~R~EQ  APPROVAL REQUEST ';
              {$endif}
              {$ifdef macc}
               mnu_FPLM_REQ       = ' ~R~EQ  APPROVAL ISSUING      Shift+F5 ';
               mnu_FPLM_REQ2      = ' R~E~Q/CHG  OPRAVA VYDANEJ PRIPOMIENKY ';
              {$endif}
               mnu_FPLM_DEP       = ' ~D~EP  FLIGHT DEPARTURE ';
               mnu_FPLM_EST       = ' ~E~ST  MESSAGE ON FLIGHT ';
               mnu_FPLM_ETO       = ' E~T~O  FLIGHT MESSAGE UPDATING ';
               mnu_FPLM_MZP       = ' ST~V~  STOPOVER ARRIVAL/DEPARTURE ';
               {mnu_FPLM_MZS      = ' MZ~S~  õTART PO MEDZIPRISTèTã ';}
               mnu_FPLM_ARR       = ' ~A~RR  FLIGHT ARRIVAL ';

               mnu_FPLM_          = ' ~F~PL ';
               mnu_FPLM_CHG_      = ' ~C~HG ';
               mnu_FPLM_CNL_      = ' C~N~L ';
               mnu_FPLM_REQ_      = ' ~R~EQ ';
               mnu_FPLM_REQ2_     = ' R~E~Q/CHG ';
               mnu_FPLM_DEP_      = ' ~D~EP ';
               mnu_FPLM_EST_      = ' ~E~ST ';
               mnu_FPLM_ETO_      = ' E~T~O~ ';
               mnu_FPLM_MZP_      = ' ST~V~ ';
               {mnu_FPLM_MZS_      = ' MZ~S~ ';}
               mnu_FPLM_ARR_      = ' ~A~RR ';

             {$ENDIF}

