     {$IFDEF SLOVAK}
       const  titEST_     = 'V˜po‡et ‡asu na trati od';
              titEST_DEP  = ' ~L~etiska ¨tartu ';
              titEST_EST  = ' ~V~stupn‚ho bodu ';
              titEST_LAST = ' ~P~osledn‚ho bodu ';
              titEST_NEXT = ' ~N~asleduj£ceho bodu ';
              titEST_NOPL = ' ~B~ez prepo‡tu ';
     {$ENDIF}


     {$IFDEF CZECH}
       const  titEST_     = 'V˜po‡et ‡asu na trati od';
              titEST_DEP  = ' ~L~eti¨tˆ startu ';
              titEST_EST  = ' ~V~stupn¡ho bodu ';
              titEST_LAST = ' ~P~osledn¡ho bodu ';
              titEST_NEXT = ' ~N~asleduj¡c¡ho bodu ';
              titEST_NOPL = ' ~B~ez p©epo‡tu ';
     {$ENDIF}


     {$IFDEF ENGLISH}
       const  titEST_     = 'Estimate times on the route points ';
              titEST_DEP  = ' ~D~eparture airport ';
              titEST_EST  = ' ~I~nput point on the route ';
              titEST_LAST = ' ~L~ast overflown point ';
              titEST_NEXT = ' ~H~eading point ';
              titEST_NOPL = ' ~N~ot calculate times';
     {$ENDIF}

