     const {$IFDEF SLOVAK}
            tit_datum_cas     = 'D tum/‡as';
            tit_den_platnosti = 'D tum platnosti pl nu';
           {$ENDIF}

           {$IFDEF CZECH}
            tit_datum_cas     = 'D tum/‡as';
            tit_den_platnosti = 'D tum platnosti pl nu';
           {$ENDIF}

           {$IFDEF ENGLISH}
            tit_datum_cas     = 'Date/time';
            tit_den_platnosti = 'Date of the plan validity';
           {$ENDIF}
