; -----------------------------------------------
; Configuration of UKBB's AFTN node....
; תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת
; ACC Kiev  (LETVIS FDP/FDA)
; -----------------------------------------------


;----------------------------
; NODES IDENTIFICATION
;תתתתתתתתתתתתתתתתתתתתתתתתתתתת

  FIR            = UKBB                ; FIR code

  THIS NODE      = UKBVZQZX            ; AFTN address (UKBVZQZX)
  ALIAS NODE     = UKBAZUZX UKBAVDU    ; another AFTN acceptable adresses
  REMOTE NODE    = *                   ; adress of accepted sources/senders -> all


;----------------------------
; AFTN LINE SETTING
;תתתתתתתתתתתתתתתתתתתתתתתתתתתת

  INPUT ADDRESS  = UKBVZQZX
  OUTPUT ADDRESS = UKBVZRZX

  INPUT CHANNEL  = VLA                 ; [1]
  OUTPUT CHANNEL = LVA

; INPUT CHANNEL  = VLV                 ; [7]
; OUTPUT CHANNEL = LVV


; תתתתתתתתתתתתת
; RS232 setup :
; תתתתתתתתתתתתת

  COM         = 2
  MODE        = 1200
  BITS        = 5
  STOP_BITS   = 2
  PARITY      = NONE


; תתתתתתתתתתתתת
; AFTN setup  :
; תתתתתתתתתתתתת

  Ts_TimeOut  = 20                     ; TimeOut [min] for sended messages
  Tr_TimeOut  = 20                     ; TimeOut [min] for received messages

  HeartBeat ID       = –• ‹
  HeartBeat PERIODE  = 2
  HeartBeat MIN      = 1

  STREAM SAVE = no                     ; archive binary AFTN data
  TEST TEXT   = ›››››››››››››››››››››››››››››››››


;-----------------------------
; AFTN MESSAGES PROCESSING
;תתתתתתתתתתתתתתתתתתתתתתתתתתתתת

  LIMIT - TLG CONFIRM = 24
  LIMIT - ERR PROCESS = 24


;-----------------------
; RPL PROCESSING
;תתתתתתתתתתתתתתתתתתתתתתת

  H-RPL = 21
  M-RPL = 13


;-----------------------
; PLN DECODE PARAMETERS
;תתתתתתתתתתתתתתתתתתתתתתת

  PLN SOH1 = ‹€ 
  PLN SOH2 =  … ‰ ‘  ’ˆ  ‚›‹…’    ‚•„      ‚›•„     ‘€„€  … €‡
  PLN EOH  = …–
  PLN ADR  = UKBZ UKZZ


;-----------------------
; FPL PROCESSING
;תתתתתתתתתתתתתתתתתתתתתתת

  PPL = enabled
  MZP = enabled
