; ------------------------------
; FDP/ACC  ACC Borispol
; ------------------------------

  SECTORS = \FDPÿDATA\MAPS\UK\SECTORS.ACC
; SECTORS = .\MAPS\SECTORS.ACC
; SECTOR  =

; -----------
; K1 MOSKVA
; תתתתתתתתתתת
  S1; SEC = K1 ;  ALT = 0

; -----------
; K2 DNEPR
; תתתתתתתתתתת
  S2; SEC = K2 ;  ALT = 0

; -----------
; K5 ODESSA
; תתתתתתתתתתת
  S3; SEC = K5 ;  ALT = 0

; -----------
; K3 LVOV
; תתתתתתתתתתת
  S4; SEC = K3 ;  ALT = 0

;------------
; K4 APP
;------------
  S5; SEC = K4 ;  ALT = S0810-S5500