;-----------------------
; FIR DESCRIBTION
;תתתתתתתתתתתתתתתתתתתתתתת

  AIRBASE = UKBB
; @DATA = .\LIST
  

;-----------------------
; SYSTEM
;תתתתתתתתתתתתתתתתתתתתתתת

; win.tmp = D:\
  time = 1

