; -----------------------------------------------
;  Komunikacny uzol medzi PVO a ASSOC
;
;  Vsetky civilne spravy (CPL i EST) sa posielaju
;  len vo formate CPL, pretoze podla Doc.4444
;  sprava EST neobsahuje pole 15 a plan nie je
;  predtym doruceny spravou FPL alebo ABI
;
; -----------------------------------------------


;---------------
; ASSOC
;תתתתתתתתתתתתתתת

  ADR IN HEADER  = no              ; enabled -> za identifikator typu spravy vlozi THIS NODE/REMOTE NODE+CISLO SPRAVY

  ITA-2 ASCII    = yes             ; enabled -> koduje ICAO spravy v cistom textovom formate bez ITA2 oddelovacov a novych riadkov
  ITA-2 BIN      = no              ; enabled -> koduje ITA-2 spravu do binarnej podoby - inverzneho patbitoveho kodu
; BITS           = 5               ; pocet bitov v binarnej vystupnej sprave



;---------------
; ADRESY
;תתתתתתתתתתתתתתת

  FIR            = LKPR            ; udaje do hlavicky spravy
  THIS NODE      = xx
  REMOTE NODE    = xx

  INPUT ADDRESS  = LKxxxxxx        ; ICAO adresa tejto stanice
  OUTPUT ADDRESS = LKxxxxxx        ; ICAO adresa prijimajucej stanice

  INPUT CHANNEL  = xxx             ; vstupny kanal
  OUTPUT CHANNEL = xxx             ; vystupny kanal


;---------------
; OLDI
;תתתתתתתתתתתתתתת

; THIS NSAP   = 49 33 00           ; volane NSAP
; REMOTE NSAP = 49 1F 00           ; volajuce NSAP

; Ts_TimeOut   = 40
; Tr_TimeOut   = 80

; send StartUp = yes               ; povolenie vysielania StartUp


;---------------
; Xת25
;תתתתתתתתתתתתתתת

; rec_buf_size = 5;                ; velkost prijimacieho buffera (az neskor a automaticky pri zmene)
; pkt_size     = 4096              ; nastavit zatial manualne do X25.camus.cfg



;---------------
; Data
;תתתתתתתתתתתתתתת

  FL from altitude = FL60;         ; od uvedenej vysky sa letove hladiny uvadzaju vo feetoch
  send VFR FPL     = yes;          ; odosielat ku ASSOC FPL letov VFR
