; ===============================================
; IPX configuration
; ATCC Kiev
; EDD/K2
; -----------------------------------------------

  S1       ; C03FCCDF  = 2
  S2       ; C011A9DE  = 3
  PRN      ; C054CCDF  = 4

  K4       ; C05ACCDF  = 5
; K4_RDP   ; C0C3CCDF  = 15

  K3       ; C03ECCDF  = 6
; K3_RDP   ; C035CCDF  = 16

  K1       ; C0D2CCDF  = 7
; K1_RDP   ; C037CCDF  = 17

  P1       ; C03CCCDF  = 8
; P1_RDP   ; C036CCDF  = 18

  K2       ; C0BACCDF  = 9   ; @THIS
  K2_RDP   ; C03BCCDF  = 19

  K5       ; C032CCDF  = $A 
; K5_RDP   ; C03BCCDF  = $1A

  MIL      ; C055CCDF  = $B
; MIL_RDP  ; C0D1CCDF  = $1B

; TS_RDP   ; C05FCCDF  = $1C
