; ===============================================
; SSR CODE  configuration file
; ATCC Kiev
; K1/MOSKVA,KHARKIV
; -----------------------------------------------

; SSR CODE = 4601-4607, 4610-4616
  SSR CODE = 4601-4603

