;-----------------------
; FIR DESCRIBTION
;תתתתתתתתתתתתתתתתתתתתתתת

  AIRBASE = LZIB


;-----------------------
; SYSTEM
;תתתתתתתתתתתתתתתתתתתתתתת

 time = 1

;-----------------------
; FUNCTIONS
;תתתתתתתתתתתתתתתתתתתתתתת

 edit FPLm = yes ; povolenie editacie vojenskeho a ineho stripu
 edit FPLc = yes ; povolenie editacie civilneho stripu

