; -------------------------------------------
; FDP/S-EDD  MACC Praha
; -------------------------------------------

; ---------------------------------------------------------------------------------------------------------
; pracovisko ; adresa                               ; Fprotokol ; Lprotokol   ; informace
; ---------------------------------------------------------------------------------------------------------


; ------------------------
; MACC - Technicke pozice
; ------------------------

  ROUTER (UDP) ; ROUTER        ,$0702, 10.192.49.100 ;            @ROUTER
  MONITORING   ; MON           ,$0703                ; ~RTU     ; @RDP        ; -slave -noinit  FPLc,FPLm,FPLo, PRS,QGO,SYN

  SERVER-A     ; MACC_SERVER   ,$0707, 10.192.49.85  ;            @THIS
  SERVER-B     ; MACC_SLAVE    ,$0708, 10.192.49.80  ; ~UDP     ; @BSERVER ~OX ; -slave -time   FPLc,FPLm,FPLo, PRS,QGO,SYN


; ------------------
; MACC - FDP pozice
; ------------------

; EDD-VYCHOD   ; EDD_VYCHOD    ,$070D, 10.192.49.84  ; ~RTU     ; @EDD      ; -slave        FPLc,FPLm,FPLo
; EDD-TEREN    ; EDD_TEREN     ,$070C, 10.192.49.82  ; ~UDX     ; @EDD      ; -slave        FPLc,FPLm,FPLo
  EDD-TFPLc    ; EDD_TFPLc     ,$070E, 10.192.49.124 ; ~RTU     ; @RDP      ; -slave        FPLc,FPLm,FPLo

; FDO-SOD      ; FDO_SOD       ,     , 10.192.49.90  ; ~UDP     ; @EDD ~NX  ; @FDA -slave   FPLc,FPLm,FPLo, PRS


  FDO-SOD      ; FDP           ,     , 10.192.49.99  ; ~UDP  ~L ; @EDD ~OX  ; -slave        ALL
