; ----------------------------
; FDP/OPL-SMD Bratislava, X25
; ----------------------------
;
; ---------------------------------------------
; nazov      uzol     adresa   doplnkove udaje
; ---------------------------------------------

  Blava    ; StrRLP ; #105   ; @BRIDGE

  Malacky  ; 100    ; #108   ;
  Iv nka   ; 150    ; #105   ;
  Pie¨Ÿany ; 200    ; #110   ;
  Tren‡¡n  ; 250    ; #107   ; @THIS
  Slia‡    ; 300    ; #109   ; 
  Ko¨ice   ; 500    ; #111   ;
  Pre¨ov   ; 600    ; #112   ;  
